ucb-bar/chipyard

- Makefrag
- build.sbt
- src/main/scala/example/Top.scala
* Update Scala version to 2.12.4 and work around SBT multi-project idiosyncrasies.
* Remove `HasSystemErrorSlave`.
All regression tests pass.
> Bump rocket-chip to 2018-09-25 commit

- src/main/scala/example/Configs.scala
- src/main/scala/example/PWM.scala
- src/main/scala/example/Top.scala
Also closes #41.
I'm using fixedWidth rather than variableWidth because it seems fragmenter doesn't interact well with the axi<->tl converter. Is there a cleaner way I should do this? @colinschmidt
> Add an AXI4 flavor of PWM peripheral.

- .gitmodules
- Makefrag
- build.sbt
- project/build.properties
- project/plugins.sbt
- verisim/Makefile
- verisim/Makefrag-verilator
- vsim/Makefile
Waiting on ucb-bar/barstools#35.
This adds barstools to project-template and changes the make targets to generate separate top and harness files, as well as generates external memories from SeqMems. By default these memories are implemented as synthesizeable flops, but this makes plugging in a VLSI flow easier.
> Add barstools

- .gitmodules
The .git suffix was dropped and git@ was used instead of https://
Update to be consistent with other submodules.
> Update gitmodule url to use https

- Makefrag
- src/main/scala/example/Simulator.scala
- verisim/Makefile
- vsim/Makefile
Barstools now handles annotations correctly.
This means that the blackboxresources for the harness
and top are different and need to be merged in the build system.
We also add all Sim*.cc files to default resources as our new emulator
demands. We then remove them from the harness .f file to avoid having
to detect which ones to include selectively.
> Bumps barstools and fixes build system after

- sims/verisim/Makefile
- sims/vsim/Makefile
fix bug where `make clean` wouldn't run since I deleted the `clean-scala` target earlier
> [rebar] fix make clean

- common.mk
Small improvement to reduce the amount of SBT calls. Should really only be called if the utilities files change or if the directory switches from `vsim` to/from `verisim`
> reduce amount of sbt calls for sim

- common.mk
- variables.mk
Have the simulation rules share the `SIM_FLAGS` variable so that people can override them if they want.
> Run Binary Default Flag Change

- generators/example/src/main/scala/ConfigMixins.scala
- generators/example/src/main/scala/Configs.scala
Based on #92 so wait until that is merged.
Allow for different RoCC accelerators to be attached to different harts. In this case, this is only for Hwacha but this can be used for other RoCC accelerators (Systolic Array).
Credit for initial work: @a0u @alonamid
> MultiRoCC Support

- .gitignore
- .gitmodules
Some submodules used ssh instead of https and some generated files were not ignored by .gitignore.
Cheers,
Bastian
> Fix minor annoyances 

- .circleci/check-commit.sh
- .circleci/config.yml
Addresses #104. Would be better to find a solution that doesn't require you to `init` all the submodules. This is just something that will temporarily work.
> Check if submodule commits are on master

- generators/example/src/main/scala/Generator.scala
Use `hartId` 0 to add the correct test suites. This is used when `hartId` 0 is not assigned to the first tile elaborated.
> use hart0 for the test suite

- generators/example/src/main/scala/Generator.scala
Clean up the generator so that it shares the TestSuites given in the BOOM generator. Hopefully, this reduces the amount of duplicated code. This can also help with mixing in new TestSuites into the Generator by having the new project to just add a function.
> use generator functions from boom | bump boom

- generators/utilities/src/main/resources/csrc/emulator.cc
Frontend-server can now ignore arguments in-between +permissive and +permissive-off, which is what the makefile run commands already do.
> Don't need to make copy of HTIF args in emulator

- common.mk
- generators/utilities/src/main/resources/csrc/emulator.cc
- sims/verisim/Makefile
- sims/verisim/verilator.mk
- sims/vsim/Makefile
Added support to change the Verilator install location. Should help with CI efforts.
> Verilator Install Location | Re-add HTIF arg parsing | Pass Errors Correctly in *.out

- generators/beagle/src/main/scala/ConfigMixins.scala
After these changes, we can still build `MegaBeagleConfig` and we pass the `mt-matmul`, `mt-vvadd`, and `dhrystone` tests. I haven't tried other tests.
> Bump systolic and fix systolic generator parameters

- common.mk
- sims/vsim/Makefile
Fixes error in VCS when there are duplicate blackbox files in the simulation.
> remove duplicate blackbox files | general grep

- .circleci/defaults.sh
- generators/example/src/main/scala/Configs.scala
Have Hwacha use the L2 during CI. This requires the config to live in `example` land. However, I use the `hwacha` generator to use the tests from their project.
This resolves the CI failures for Hwacha.
> Hwacha CI Update

- scripts/init-submodules-no-riscv-tools.sh
This allows the user to not run the `unset` command after the init script to update the submodules.
> Unset the init for `hammer-cad-plugins`

- scripts/build-toolchains.sh
When you run `env.sh` now, it clobbers the `LD_LIBRARY_PATH`. Instead, it should just append to it. Is there a specific reason for not being an append?
> Do not clobber LD_LIBRARY_PATH in env.sh

- common.mk
This avoids name conflicts between the design top and the test harness by coordinating the two FIRRTL compiler runs into one invocation of the main generator app. It also makes Verilog simulator generation somewhat faster.
Coordinated with ucb-bar/barstools#63
> Coordinate Top and Harness generation

- .circleci/config.yml
We decided this was a bad idea, and that submodules should just avoid rebase-commits.
> Only check commit-on-master on master

- generators/example/src/main/scala/Generator.scala
- generators/example/src/main/scala/TestSuites.scala
Thinking everything was fine... I pressed the merge button on the #176 PR without looking at the CI. This should fix the problem.
Most tests are the same between BOOM and Rocket with slight differences (removed the breakpoint and BOOM specific test suites since now we match with Rocket)
> re-add testsuites to compile

- build.sbt
- generators/example/src/main/scala/Generator.scala
- generators/firechip/src/main/scala/Generator.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
- generators/utilities/src/main/scala/TestSuites.scala
These commits are needed in order to fix firesim-as-library compilation. Now example and firechip share the assembly test and benchmark generation.
> Fix firesim test suite generation

- build.sbt
- common.mk
- docs/Customization/Adding-An-Accelerator.rst
- generators/firechip/src/main/scala/TargetConfigs.scala
- generators/firechip/src/main/scala/TargetMixins.scala
- generators/firechip/src/main/scala/Targets.scala
- generators/tracegen/src/main/scala/Configs.scala
- generators/tracegen/src/main/scala/System.scala
- generators/tracegen/src/main/scala/TestHarness.scala
- generators/tracegen/src/main/scala/Tile.scala
- scripts/check-tracegen.sh
- variables.mk
This PR adds support for the TraceGen tool, which is used to verify cache coherence. You can now use TraceGen in VCS/Verilator SW simulation or in FireSim SW simulation.
> Add TraceGen project

- scripts/build-static-libfesvr.sh
- scripts/build-toolchains.sh
- scripts/check-tracegen.sh
- scripts/firesim-setup.sh
- scripts/init-submodules-no-riscv-tools.sh
- scripts/init-vlsi.sh
Included are miscellaneous changes to address some less known edge cases with the shell scripting and improve clarity and maintainability.
* Parse command-line options with the `getopts` builtin.
* Fix quoting to tolerate paths with whitespace characters.
* Set make jobs based on hardware thread count instead of a hard-coded value (16).
> Improve robustness/portability of toolchain shell scripts

- .circleci/build-verilator.sh
- .circleci/defaults.sh
- .circleci/do-rtl-build.sh
- .circleci/run-tests.sh
- common.mk
- sims/verilator/Makefile
This should now allow developers to run `make -jX` with the build system. It makes it so that a "temp" file is the sole target of the main recipe and the real targets depends on the "temp" target.
Followed: https://stackoverflow.com/questions/19822435/multiple-targets-from-one-recipe-and-parallel-execution
Fixes #147 and addresses part of #211.
> Make parallel support

- .gitmodules
- build.sbt
- project/plugins.sbt
Recently, the sonatype URL we were using to pull in firrtl-interpreter stopped working. This commit adds firrtl-interpreter as a submodule and switches to including it as a project in the build.sbt instead.
> Make firrtl-interpreter a submodule instead of depending on external snapshot

- sims/vcs/Makefile
- sims/verilator/Makefile
This fixes `run-asm-tests-debug`.
We can't have a test case to test the `run-XXX-debug` targets because the Makefiles need to generate vpds with the vcd2vpd utility.
> Make .vpd rules generate the .out as well

- generators/example/src/main/scala/BoomConfigs.scala
The UnifiedBoomConfig is burdensome to maintain. We are removing that configuration option from BOOM, so we should not reference that option here.
> Replace UnifiedBoomConfig with SmallRv32BoomConfig

- .gitmodules
- build.sbt
- generators/firechip/src/main/scala/TargetConfigs.scala
* ucb-bar/sha3#14: Conform to the finalized FIPS 202 standard.
* ucb-bar/sha3#15: Fix virtual memory interaction with interrupts.
This was tested on FireSim.
> Bump SHA-3 accelerator for tutorial enhancements

- docs/VLSI/Tutorial.rst
- vlsi/view_gds.py
This adds a script for the tutorial to use `gdspy`'s LayoutViewer to look at the GDS.
> View GDS w/ gdspy

- .circleci/config.yml
- scripts/build-toolchains.sh
`RDIR` (the initial working directory) is not necessarily the top of the chipyard source tree, such as how the CI invokes `build-toolchains.sh`.
Fixes #267.
> Fix SRCDIR for qemu build

- docs/Chipyard-Basics/Development-Ecosystem.rst
- docs/Tools/Chisel.rst
- docs/Tools/FIRRTL.rst
Use the new website links. `chisel.eecs.berkeley.edu` will properly redirect. However, `freechipsproject.github.io/firrtl` is legacy at this point.
> Use new website links

- scripts/build-toolchains.sh
This adds another `env.sh` that is specific to the toolchain that is built. This makes it so that the `env.sh` does not get clobbered.
> Add a specific toolchain `env.sh`

- .circleci/check-commit.sh
- scripts/init-submodules-no-riscv-tools.sh
This does @sagark's recommendation to print out all the failures and exit only at the end of the script. Additionally, it deals with the flattened toolchain folders.
> Fix `master` CI

- build.sbt
- generators/firechip/src/main/scala/Targets.scala
This provides an example design with a GCD MMIO peripheral with a Verilog blackbox in FireChip. It can be pushed through FPGA simulation with firesim/firesim#388 and ucb-bar/midas#150.
> Add Verilog blackbox FireSim simulation example

- vlsi/Makefile
The `SMEMS_FILE` was supposed to be `TOP_SMEMS_FILE`
> Fix VLSI Makefile

- common.mk
Without the end-of-line marker, the grep rule would match file paths with a ".h" anywhere in the path. For instance, if you have a configuration that begins in h (either upper or lower case), it would match on 
generated-src/example.TestHarness.HwachaConfig/TestDriver.v
Causing the file to inappropriately omitted from sim_files.common.f
> make sure grep filter only omits .h files

- .gitmodules
This adds SPEC2017 and CoreMark workloads that work with FireMarshal. Additionally, it bumps `firesim` so that you can get the updated FireMarshal tool.
> SPEC2017 + CoreMark + FireSim/FireMarshal Bump

- vlsi/Makefile
Splits `vlsi/build` on the type of design.
Covers #220. Fixes #187
> Partition `vlsi/build` on design

- .circleci/do-firesim-build.sh
This is bumping `barstools` to have a couple of macro-compiler bug fixes and cleanup.
> Bump Barstools

- .circleci/check-commit.sh
- .circleci/config.yml
This works by checking the $CIRCLE_BRANCH env-var, which is set automatically by
CircleCI. Annoyingly, this is set to the name of the source branch for a merge,
rather than the target branch. The behavior of this check for each branch type
is listed:
```
if CIRCLE_BRANCH == "master":
This CI run is the nightly CI run for the master branch.
Make sure all submodules of the master branch point to master
else if CIRCLE_BRANCH == "dev":
This CI run is most likely somebody doing a dev->master merge.
Make sure all submodules of the dev branch point to master
else:
This CI run is likely somebody merging a feature branch into dev.
Allow submodule pointers of the feature branch to point to master OR dev
```
> [ci] Whitelist submodule dev branches for commit-on-dev checks

- .ctagsignore
- scripts/gen-tags.sh
This PR makes it so that you don't parse `sims/*` or the `toolchains` folder for ctags. This drastically reduces the runtime (prevents you for looking through riscv-linux) and the filesize of the tags file. Additionally, it also just parses Scala, C, C++, and Python files.
> Cleanup Ctags

- generators/example/src/main/scala/ConfigMixins.scala
- generators/example/src/main/scala/HeteroConfigs.scala
Example MultiCore configuration with a small "control" core attached on the side (i.e. a PMU). This was requested by @jwright6323 and @alonamid.
> Control Core Example

- build.sbt
- generators/example/src/main/scala/Generator.scala
- generators/example/src/main/scala/TestHarness.scala
- generators/firechip/src/main/scala/BridgeBinders.scala
- generators/firechip/src/main/scala/Generator.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
- generators/tracegen/src/main/scala/TestHarness.scala
- generators/utilities/src/main/scala/Subsystem.scala
- variables.mk
This is a subset of my previous PR with only the bumping changes. 
Things work locally so hopefully I don't many if any CI failures.
> Bump all submodules for chisel 3.2.0 and rocket-chip august-2019

- .circleci/check-commit.sh
Chisel3 and FIRRTL use release branches, which we track instead.
> Do not check that chisel3 and firrtl submodule branches are whitelisted

- .circleci/config.yml
- scripts/build-toolchains.sh
I like to manage my `$RISCV` independently.
> Let user specify existing PREFIX/RISCV for toolchain installs

- docs/Generators/Gemmini.rst
I removed the instructions for writing your own Gemmini programs, until we can figure out a better, more intuitive build process for letting users do so.
> Update gemmini docs

- build.sbt
- docs/Generators/TestChipIP.rst
- generators/example/src/main/scala/BoomConfigs.scala
- generators/example/src/main/scala/ConfigMixins.scala
- generators/example/src/main/scala/HeteroConfigs.scala
- generators/example/src/main/scala/RocketConfigs.scala
- generators/example/src/main/scala/TestHarness.scala
- generators/example/src/main/scala/Top.scala
This PR adds a UART to all systems and adds a UARTAdapter in the TestHarness to talk to the UART.
Things to do:
> Add UART and UARTAdapter to all configs

- common.mk
Occasionally, parallel `make` will silently ignore source file changes. See #377 and https://stackoverflow.com/questions/19822435/multiple-targets-from-one-recipe-and-parallel-execution/. This attempts to address this issue by adding a `touch` to the targets depending on the `INTERMEDIATE` value.
This was tested by doing `make -j32` on the config./system listed in #377. 
Fixes #377
> Patch parallel make

- generators/example/src/main/scala/ConfigMixins.scala
- generators/example/src/main/scala/RocketConfigs.scala
- generators/example/src/main/scala/Top.scala
- generators/example/src/main/scala/TopCakes.scala
Fixes #381.
Adds a configuration that removes off-chip memory interface in favor of a configurable scratchpad hanging off the `mbus`. This builds Verilog but I haven't tested any code with this. 
Based on #347 so this must go in after that. (Ill change the base branch when the other PR is done).
> Scratchpad Config

- .circleci/config.yml
- .circleci/defaults.sh
- .circleci/run-tests.sh
- build.sbt
- generators/tracegen/src/main/scala/Configs.scala
- generators/tracegen/src/main/scala/System.scala
- generators/tracegen/src/main/scala/Tile.scala
> [tracegen] Add tracegen support for the BOOM L1D

- common.mk
If you look at the CI, there are multiple points where the `HwachaRocketConfig` fails during a MacroCompiler step with the following:
- `java.lang.NoClassDefFoundError: mdf/macrolib/PortPolarity`: https://circleci.com/gh/ucb-bar/chipyard/12736
- `java.lang.ClassFormatError: Truncated class file`: https://circleci.com/gh/ucb-bar/chipyard/13029
I haven't been able to replicate the error (yay non-determinism), but I theorize that this is a problem with 2 `sbt` runs on the same binary (e.g. MacroCompiler) running at the same time (since all our CI uses parallel `make`). `sbt` seems to only lock at the beginning when looking up things in ivy, so if MacroCompiler is getting compiled twice, it might clobber files?
This is a proposed solution by making the MacroCompiler serialized by having an …
> Enforce that macrocompiler passes are done serially

- scripts/init-submodules-no-riscv-tools.sh
This is a draft PR to demonstrate the top-level fix for the excessive riscv-linux cloning issue.
Once firesim is bumped with the midas flattening, we don't need to clone any firesim submodules except for FireMarshal.
Deprecate the `--no-firesim` switch (which did not work correctly anyway).
> Clone firesim non-recursively

- generators/example/src/main/scala/HeteroConfigs.scala
FIxes the `DualLargeBoomAndHwachaRocketConfig` elaboration error where it can't find the "HwachaLanes" parameter since the `DefaultHwachaConfig` was not added.
> Fix multi-rocc boom+rocket+hwacha config

- common.mk
- sims/vcs/Makefile
- sims/verilator/Makefile
Thanks to @a0u for the fix.
This was messing up `tee`, causing spurious test failures with VCS.
This also fixes having to `reset` after running VCS simulations to get back `stdout`
**Note**: Verilator isn't affected, but do the same thing anyways to have uniform behavior across simulators.
> [sim] Pipe /dev/null to simulators to fix VCS messing up stdout

- generators/firechip/src/main/scala/TargetConfigs.scala
- generators/firechip/src/main/scala/TargetMixins.scala
Since BOOM does not drive the trace port by default, TracerV was capturing an empty trace. 
Enables trace capture by default in BOOM-based FireChip targets.
> [firechip] Enable trace by default in BOOM-based targets

- scripts/build-toolchains.sh
- scripts/firesim-setup.sh
- scripts/init-submodules-no-riscv-tools.sh
This fixes the env.sh generation for weirdos like me.
**Type of change**: A matter of perspective
**Impact**: software change 
Make references to `BASH_SOURCE` also provide a `zsh` compatible default.
> Fix generation of env.sh for zsh

- scripts/init-submodules-no-riscv-tools-nolog.sh
- scripts/init-submodules-no-riscv-tools.sh
**Related issue**: Fixes #426 
Log the setup scripts to help users debug (`init-submodules` and `build-toolchains`). Follows the recommendation given in #426.
> [setup] log init submodules

- docs/Advanced-Concepts/CDEs.rst
- docs/Advanced-Concepts/Chip-Communication.rst
- docs/Advanced-Concepts/Top-Testharness.rst
- docs/Advanced-Concepts/index.rst
- docs/Chipyard-Basics/Configs-Parameters-Mixins.rst
- docs/Customization/Heterogeneous-SoCs.rst
- docs/Customization/IOBinders.rst
- docs/Customization/Keys-Traits-Configs.rst
- docs/Customization/MMIO-Peripherals.rst
- docs/Customization/Memory-Hierarchy.rst
- docs/Customization/index.rst
- docs/Generators/Gemmini.rst
- docs/Generators/Hwacha.rst
- docs/Generators/IceNet.rst
- docs/Generators/SHA3.rst
- docs/Generators/SiFive-Generators.rst
- docs/Generators/TestChipIP.rst
- docs/Simulation/FPGA-Accelerated-Simulation.rst
- docs/Simulation/Software-RTL-Simulation.rst
- generators/chipyard/src/main/scala/ConfigFragments.scala
- generators/chipyard/src/main/scala/GCD.scala
This renames all instances of config mixins to fragments to better distinguish between traits/mixins that apply to the `Top` and config fragments that make configs.
> Rename Config Mixins to Fragments

- .circleci/config.yml
- .circleci/images/Dockerfile
- .circleci/images/README.md
**Related issue**: #448 
This moves the Docker image from `riscv-boom/riscv-boom` to Chipyard and also moves the remote repository into the `ucbbar` Docker-Hub account. This should wait until #448 is complete before being merged (to get the correct Verilator version).
This also bumps BOOM to `master` (includes bugfixes and docker image removal).
> Move DockerImage into Chipyard + Bump BOOM

- scripts/build-util.sh
On macOS, "gnumake" and "make" are both supplied by the OS, but are too old to build glibc (both are version 3.81 as of this writing). Homebrew provides the "gmake" executable, which is recent enough for glibc. However, the existing logic in "scripts/build-util.sh" will always prefer "gnumake" over "gmake".
The configure logic in the riscv-glibc library allows a user to override the preference for "gnumake" by setting the MAKE environment variable. This change makes "scripts/build-openocd.sh" and "scripts/build-toolchains.sh" mimic that behavior. A user can now use "gmake" instead of "gnumake" during the toolchain build like so:
MAKE=gmake ./scripts/build-toolchains.sh
> Allow user to override MAKE command used by toolchain and openocd build

- scripts/ubuntu-req.sh
The "libxpat1-dev" package doesn't exist on Ubuntu/Debian, and results in an error when installing Ubuntu/Debian dependencies.
The desired package: https://packages.ubuntu.com/bionic/libexpat1-dev
> [Documentation] Fix name of Ubuntu/Debian package "libexpat1-dev".

- .circleci/config.yml
- docs/Generators/IceNet.rst
- docs/Makefile
- docs/TileLink-Diplomacy-Reference/Widgets.rst
- docs/Tools/Barstools.rst
- docs/VLSI/Building-A-Chip.rst
**Related issue**: Fixes #483 
This runs CI on the documentation to make sure that documentation changes still build properly (very strict checking and errors as soon as possible).
> [docs/ci] cleanup docs and add ci to check it

- generators/chipyard/src/main/scala/config/BoomConfigs.scala
- generators/firechip/src/main/scala/BridgeBinders.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
> refer to testchipip traceio in firechip

- generators/chipyard/src/main/scala/ConfigFragments.scala
- generators/chipyard/src/main/scala/config/BoomConfigs.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
Use one TraceIO fragment everywhere.
> [sboom] Move TraceIO fragment to chipyard

- .circleci/config.yml
CI now doesn't automatically run. Instead, a person with access to the CI (i.e. Chipyard developers) can click the approve button to run CI.
> CI Run Button

- sims/verilator/Makefile
The 'debug' rule is currently cleaning out the non-debug-model directory rather than the debug-model directory. This means a debug-mode build would cause the non-debug-mode build to get cleared out.
This PR fixes that, and changes both the debug and non-debug rules to use the variables defined for referring to these two model directories.
> Fix bug in verilator Makefile for 'debug' rule

- .circleci/config.yml
Bypasses the `ci-approval` job in CI so that developers don't have to approve CI to run on `dev` and `master` branches.
> Bypass approval button on dev/master

- docs/Simulation/Software-RTL-Simulation.rst
**Related issue**: On computers with limited resources (like main memory) the elaboration will fail with the message 'make: *** [firrtl_temp] Error 137'. Since no further explaination of the error is given, its meaning should be mentioned in the docs. See issue #455 
Added note to docs about error message when elaborating configuration on systems with little main memory.
> Added note about resource usage during elaboration to docs

- .circleci/config.yml
**Related issue**: #510 
Remove the CI run button so that CI runs without explicit approval. We will revisit how to deal with external PRs later.
> Remove approval button for ci jobs

- docs/index.rst
Related to #455, #436 and #514: Users forget to install dependencies because there is no reference in the quick start documentation
**Impact**: documentation
> Include scripts for dependencies in documentation

- generators/firechip/src/main/scala/Generator.scala
**Related issue**: https://github.com/firesim/firesim/issues/537
Artefacts are being dropped when running the FireSim generator since the `generateArtefacts` function is using `midas.rocketchip.util.ElaborationArtefacts` instead of `freechips.rocketchip.util.*` (the MIDAS `ElaborationArtefacts` is never appended to while the RC `ElaborationArtefacts` is used everywhere else). This fixes this issue.
> Generate Rocket Chip based artefacts in FireSim

- .circleci/config.yml
- .circleci/defaults.sh
- .circleci/run-tests.sh
- common.mk
- generators/chipyard/src/main/scala/unittest/TestHarness.scala
- generators/chipyard/src/main/scala/unittest/UnitTestSuite.scala
- sims/vcs/Makefile
- sims/verilator/Makefile
- variables.mk
IceNet and TestChipIP previously had their own generators and testharnesses in order to run unittests. But now that generators can use configurations in other packages, that isn't necessary any more. Ideally, we'd be able to use the freechips.rocketchip.unittest TestHarness directly, but unfortunately it doesn't output the *.plusArgs file, which is necessary for verilator. 
https://github.com/firesim/icenet/pull/24
https://github.com/ucb-bar/testchipip/pull/78
Support for running IceNet and TestChipIP unit tests
> Get icenet and testchipip unit tests working

- docs/Customization/Heterogeneous-SoCs.rst
**Related issue**:#535
**Impact**:other
This fixes the `WithHeterCoresSetup` config. fragment to correctly use a list to combine all Tile parameters instead of `++`.
> Fix "WithHeterCoresSetup" in hetero. docs

- .circleci/config.yml
- .gitmodules
- common.mk
- docs/Customization/Heterogeneous-SoCs.rst
- generators/chipyard/src/main/scala/ConfigFragments.scala
- generators/chipyard/src/main/scala/IOBinders.scala
- generators/chipyard/src/main/scala/System.scala
- generators/chipyard/src/main/scala/config/ArianeConfigs.scala
- generators/chipyard/src/main/scala/config/BoomConfigs.scala
- generators/chipyard/src/main/scala/config/HeteroConfigs.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- generators/chipyard/src/main/scala/config/TracegenConfigs.scala
- generators/chipyard/src/main/scala/config/TutorialConfigs.scala
- generators/chipyard/src/main/scala/stage/ChipyardStage.scala
- generators/chipyard/src/main/scala/stage/phases/AddDefaultTests.scala
- generators/chipyard/src/main/scala/stage/phases/GenerateTestSuiteMakefrags.scala
- generators/firechip/src/test/scala/ScalaTestSuite.scala
- generators/tracegen/src/main/scala/System.scala
- generators/utilities/src/main/resources/csrc/emulator.cc
> Rocket Chip Bump with Chisel 3.3 and FIRRTL 1.3

- build.sbt
- common.mk
1.3 has landed -- yay! Time to use the new features.
FIRRTL now provides an assembly task for `test`, which packages up a bunch of test classes that are useful for testing firrtl passes _outside_ of firrtl. This PR calls out to `test:assembly` and drops teh resulting jar in `test_lib`. Subprojects that want to use these classes (under the `firrtl.testutils` package) may either use this new directory as their unmanagedBase, or add the resulting jar to their classpath.
I picked `test_lib` to mirror what was done in RC.
**Type of change**: new feature 
Assemble the firrtl-test.jar; put in separate unmanaged directory "test_lib"
> Assemble the firrtl-test.jar and put it in its own directory

- .gitmodules
- docs/Advanced-Concepts/Debugging-BOOM.rst
- docs/Advanced-Concepts/Debugging-RTL.rst
- docs/Advanced-Concepts/index.rst
- docs/Chipyard-Basics/Chipyard-Components.rst
- generators/chipyard/src/main/scala/Subsystem.scala
**Related issue**: https://github.com/riscv-boom/riscv-boom/pull/462 https://github.com/firesim/firesim/pull/556 https://github.com/ucb-bar/testchipip/pull/85
**Impact**: rtl change + other
This addresses the comments in the #523 and https://github.com/ucb-bar/testchipip/pull/79 PRs. I moved the BOOM Dromajo documentation to a new file and also cleaned up the TraceIO to not have 1.B wires.
> Dromajo + TraceIO Cleanup

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/question.md
This "forces" bug report writers to tell us about their environment (CY version, OS, etc) and also tries to redirect issues with Chipyard to bug reports (makes "Questions" more of a how-to, or why this way question instead of why does it not work)
> small cleanup to issues

- scripts/init-submodules-no-riscv-tools-nolog.sh
The submodule initialization script has been updated to no longer check out the now-inlined MIDAS project as a submodule of FireSim (see firesim/firesim#400).
> Don't try to init nonexistent midas submodule

- docs/Customization/Memory-Hierarchy.rst
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
**Related issue**: #567 
Fixes the docs.
> Scratchpad Documentation Fix

- generators/utilities/src/main/resources/csrc/emulator.cc
- sims/vcs/Makefile
- sims/verilator/Makefile
- variables.mk
Fixes #563 
Verilator now supports `+permissive` and now can be passed its runtime arguments such as `+verilator+rand+reset+0`
> Upgrade verilator to support permissive args in the same way as vcs

- generators/chipyard/src/main/scala/IOBinders.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
Move all non-synthesizable constructs and models into the test harness and out of ChipTop
> Move all non-synthesizable constructs into the test harness

- .circleci/build-toolchains.sh
- .circleci/clean-old-files.sh
- .circleci/defaults.sh
- .circleci/do-rtl-build.sh
- .circleci/install-verilator.sh
- .circleci/run-firesim-scala-tests.sh
- .circleci/run-midasexamples-tests.sh
- .circleci/run-tests.sh
This PR reduces the number of leftover folders left on the build server after a PR is finished. Additionally, it only allows one set of build folders on the remote server per PR i.e. only one set for the latest commit (previously: if you commit a lot to a PR, you will have a set of folders for each commit). It also adds the `COURSIER_CACHE` export to the build and distinguishes between the remote/CI num. processors for `-j`.
This hopefully reduces the amount of throttling happening on the build server.
> Small CI Improvements

- docs/Generators/Gemmini.rst
- scripts/init-submodules-no-riscv-tools-nolog.sh
**Type of change**: bug fix | new feature
**Impact**: rtl change | software change
Bump Gemmini to v0.3:
* Strided A-loads to support convolutions on Gemmini without im2col
* Optional “scaled move-ins” function to support matrix-scalar multiplications
* Experimental new “max-pooling” feature
* Added support for ONNX-to-Gemmini flow through the ONNX Runtime tool
* Removed software padding from neural network workloads, since hardware padding is now supported, and added support for new convolutions to software tests
* Moved residual additions from CPU to Gemmini, except in cases where scaling factor is greater than 1
* Various bug fixes in hardware and software
> Gemmini v0.3 Bump

- vlsi/Makefile
Fix small issues with hammer-sim dut name and flags.
It would be cool to only build dramsim when our config includes
dramsim but this matches the way the other simulators handle this
in chipyard.
We also strip out empty CC flags because hammer doesn't prune these.
Its unclear whether the hammer should handle this itself or not,
if it eventually does we can remove this check.
> Add dramsim_lib as a dependency of hammer sims

- vlsi/Makefile
- vlsi/power.mk
- vlsi/sim.mk
Symlink dramsim2 into hammer-sims rundirs
update some hammer generated makefile targets that were missed before
bump barstools to get an iocell fix
I'm currently running a design through the flow again to verify that the new iocell change works as intended. I've verified that dramsim now correctly find the ini files, and we have all the up-to-date hammer auto-generated makefile targets.
> More fixes for post-syn/par hammer simulations

- generators/utilities/src/main/resources/csrc/emulator.cc
- sims/vcs/dramsim2_ini
- sims/verilator/Makefile
- sims/verilator/dramsim2_ini
- variables.mk
- vlsi/Makefile
verilator supports the amount of `vpi` we need to do our own argument parsing without messing with emulator.cc every time.
> Allow dramsim_ini folder to be set at the command line

- vlsi/Makefile
Enable parallel simulations in hammer
> Enable parallel hammer simulations

- .circleci/run-tests.sh
- common.mk
- sims/vcs/Makefile
- sims/verilator/Makefile
- variables.mk
* Dump run-binary files in `output/$(long_name)` instead of current directory
* Remove run-none rules, these were equivalent to run-binary BINARY=none
> Use output_dir for run-binary logs and waveforms

- .githooks/ignore-certain-dirs-commit-msg
This more accurately describes what the array contains.
> Use an accurate name for the ci skip list

- generators/chipyard/src/main/scala/Subsystem.scala
**Related issue**: firesim/FireMarshal#152
This inserts an `htif` node into the boot ROM devicetree, which avoids the need for certain firmware hacks:
```
htif {
compatible = "ucb,htif0";
};
```
In FireSim, this is required to convince OpenSBI to register the HTIF-based reset handler for graceful poweroff.  It also eliminates a hardcoded fix in bbl for the same purpose: firesim/riscv-pk@bbae01a745070fea0e0e14c79cdf059257301913.
The change applies unconditionally to all Chipyard designs.  Although possibly undesirable for chips that are intended to run untethered, I believe it is largely safe in practice:
* Currently all simulation infrastructure provides `fesvr`.
* SBI implementations generally prioritize real devices above HTIF …
> Emit htif node in device tree

- .gitignore
- common.mk
- project/plugins.sbt
- scripts/firesim-setup.sh
- variables.mk
This PR brings up support for [bloop](https://scalacenter.github.io/bloop/) to do scala source compiles and for invoking scala executables. Builds/runs with bloop are enabled by setting ENABLE_BLOOP=1. I'll add documentation explaining installation.
The Bloop flow is faster across the board, but for a common iteration loop, where i touch a scala source (IOBinder.scala) and regenerate verilog (`make verilog` in sims/verilator) i've measured:
F1 c4.4xlarge: 5m21s SBT, 3m04s Bloop  (2 previous elaborations)
My 2019 mbpro:  3m4s SBT, 1m47s Bloop  (1 previous elaboration)
Neither build tool recompiles sources since i've only touched the files, but bloop seems to be ~30% faster compiling chipyard's sources.  For the figures above, much of the win comes from not having to relaunch SBT …
> Bloop Support 

- common.mk
On a typical manager instance, editing a scala file and typing make leads to a long  during which Make resolves all possible implicit rules on all prerequisites which includes 1000+ scala files. Disabling the builtin suffix rules produces a nice speedup:
On my manager instance: 
/usr/bin/time make -n: 52s -> 0.25s
On millennium:
/usr/bin/time make -n: 1.52s -> 0.17s
* Improve make performance on systems running Make 3.*
> Disable all make suffix rules for improved EC2 performance

- docs/Customization/Heterogeneous-SoCs.rst
- generators/chipyard/src/main/scala/ConfigFragments.scala
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/config/ArianeConfigs.scala
- generators/chipyard/src/main/scala/config/BoomConfigs.scala
- generators/chipyard/src/main/scala/config/HeteroConfigs.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- scripts/tutorial-patches/RocketConfigs.scala.patch
I originally argued for the value of fully flattened Configs, for better visibility of configuration options. However, with the addition of IOBinders, further divergence from Rocketchip's BaseConfig, and more supported configurations, its clear this approach is unsustainable. What took 5 lines to express in v1.0, now takes 16. This PR deduplicates a `ChipyardBaseConfig` across all existing standard Chipyard configs.
`TutorialConfigs` is left fully flattened, as that structure may be useful for education.
We should discuss the changes in the next Chipyard meeting.
> Deduplicate across Chipyard configs into a ChipyardBaseConfig

- generators/chipyard/src/main/scala/ConfigFragments.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
This avoids target software needing to explicitly set the divisor to match the [UART bridge](https://github.com/firesim/firesim/blob/f5374ffcdfdac657245274670ba18577fb8561c9/sim/firesim-lib/src/main/scala/bridges/UARTBridge.scala#L48).
> Override default baud rate for FireChip

- generators/firechip/src/main/scala/TargetConfigs.scala
This is a convenience for eventually getting zynq back up in FireSim. 
**Impact**: other 
- Add a small FireChip config that should fit on all FireSim hosts
> [firechip] Add a small target that should fit on all hosts

- common.mk
- generators/tracegen/tracegen.mk
- sims/vcs/Makefile
- sims/verilator/Makefile
- vcs.mk
Setting `RANDOM_SEED` now lets you control the random seed for VCS and Verilator. Leaving `RANDOM_SEED` unset results in randomly generated seed.
**Type of change**:  new feature
> Add RANDOM_SEED variable to set random init for VCS and Verilator simulations

- docs/Simulation/Software-RTL-Simulation.rst
- variables.mk
**Related issue**: https://github.com/ucb-bar/testchipip/pull/94
Implement fast loadmem feature for VCS/Verilator simulation
> Implement fast loadmem feature

- common.mk
- docs/Simulation/Software-RTL-Simulation.rst
- generators/utilities/src/main/resources/csrc/emulator.cc
- scripts/smartelf2hex.sh
- variables.mk
This build on #635 to add a `run-binary*-hex` target that creates a hex file from the executable and loads it for simulation.
This speeds up simulations for large executables considerably. 
Requires https://github.com/ucb-bar/esp-isa-sim/pull/16
> Esp tsi loadmem

- .gitignore
- common.mk
- docs/Simulation/Software-RTL-Simulation.rst
- sims/vcs/Makefile
- sims/verilator/Makefile
- tools/dromajo/dromajo.mk
- variables.mk
- vcs.mk
- vlsi/Makefile
**Related issue**: #562
This is a split of PR #562 with Makefile change minus the Multi-threading support. It includes changes to VCS so that it aligns with the same changes done to Verilator.
> Make help target and VCS/Verilator Cleanup

- common.mk
- docs/Simulation/Software-RTL-Simulation.rst
- generators/utilities/src/main/resources/csrc/emulator.cc
- scripts/numa_prefix
- sims/verilator/Makefile
**Related issue**: Split up from PR #562 
This splits up #562 to just include the multi-threaded Verilator improvements. The main differences from the prior PR is that `numa_prefix` is moved to `scripts/`, `numa_prefix` is directly pointed to in `common.mk`, and `NUMA_PREFIX` is added in more places (only where Verilator might be called).
Finally, I caught extra flags being passed to `LDFLAGS` that were unneeded and used the `TRACE_OPTS` that was missed in PR #650 .
> Multithreaded Verilator

- docs/Simulation/Software-RTL-Simulation.rst
- sims/common-sim-flags.mk
- sims/vcs/Makefile
- sims/verilator/Makefile
- vcs.mk
**Related issue**: Fixes #653 
Requires PR #654 to go be merged 1st. This PR deduplicates the simulator flags in Chipyard, does some minor VCS cleanup to put its `csrc` directory in a similar place to Verilator, and removes the need for the `libpthread` library.
This is tested on multi-threaded Verilator, normal Verilator, as well as VCS.
> Dedup simulation flags + Small VCS Cleanup

- common.mk
This should drastically improve performance for users who store lots of stuff in `$(base_dir)`.
In my workspace, running out of `/nscratch`, this change improved runtime of `make` with no source changes from 60 seconds to 3 seconds.
> Don't run find in base_dir to avoid slow filesystem search

- .circleci/config.yml
- .circleci/defaults.sh
- .circleci/run-tests.sh
- docs/Advanced-Concepts/Chip-Communication.rst
- generators/chipyard/src/main/scala/ConfigFragments.scala
- generators/chipyard/src/main/scala/IOBinders.scala
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/config/ArianeConfigs.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- generators/chipyard/src/main/scala/config/TutorialConfigs.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
`rocketchip.debug.DebugIO` has a bunch of stuff that should not be punched offchip through the IOCell generators.
Only punch out the subset of signals relevant to a real chip, namely the JTAG or clockedDMI signals.
This PR also bumps various riscv toolchain components that should have been bumped earlier. The dmiRocketconfig is also added to the regressions.
> Only punch realistic subset of DebugIO through chiptop | default to JTAG+Serial

- generators/firechip/src/main/scala/BridgeBinders.scala
> Undo regression in iocells flexibility

- .circleci/config.yml
- .circleci/defaults.sh
- .circleci/do-rtl-build.sh
This avoids lots of redundant time copying sources to/from build instances, and rebuilding all the Scala
> Improve CI build times by grouping similar builds

- scripts/smartelf2hex.sh
> Fix smartelf2hex.sh creating files 64x the minimum size

- generators/firechip/src/main/scala/BridgeBinders.scala
**Impact**: adds new annotations only
**Release Notes:**
Rocket- and BOOM-based tiles are now pre-annotated to enable resource optimizations in FireSim (see firesim/firesim#636).
This also bumps FireSim to include firesim/firesim#636.
> Add model multi-threading annotations (ignored by default) to FireChip

- scripts/ubuntu-req.sh
Qemu build failed on Ubuntu 18.04/20.04 hosted on google cloud without this.
bug fix | other
> added gettext dependency for qemu build

- generators/utilities/src/main/scala/Simulator.scala
The original inheritance structure for our various htif_t implementations was 
```
- htif_t (upstream riscv-tools)
- firesim_fesvr_t
- tsi_t (forked with custom mods in esp-isa-sim)
```
The new inheritance structure is
```
- htif_t (upstream riscv-tools)
- tsi_t (upstream riscv-tools)
- testchip_fesvr_t (adds loadmem support)
- firesim_fesvr_t
```
Users no longer have to install esp-tools to get loadmem support in CY SW sims.
Additionally lots of duplicated code between upstream tsi_t and firesim_fesvr_t is removed.
Future new features that are too controversial for upstream tsi_t can be added to testchip_fesvr_t.
> Unify htif implementation with firesim

- generators/firechip/src/main/scala/BridgeBinders.scala
This will make multi-threading a bit harder to use until firesim/firesim#647 is merged and makes it back to CY, but it doesn't break any code, so it's fine to merge any time.
> Don't annotate cores with FAMEModelAnnotations

- scripts/smartelf2hex.sh
elf2hex writes zeros to a segment for which MemSize > FileSize, which adheres to the ELF spec. 
Thus, we should calculate the total size of the file from the MemSize of the last segment, rather than the FileSize.
From `man elf`: 
```
The array element specifies a loadable segment,
described by p_filesz and p_memsz.  The bytes from
the file are mapped to the beginning of the memory
segment.  If the segment's memory size p_memsz is
larger than the file size p_filesz, the "extra"
bytes are defined to hold the value 0 and to follow
the segment's initialized area.  The file size may
not be larger than the memory size.  Loadable seg‐
ment entries in the program header table appear in
ascending order, sorted on the p_vaddr member.
```
**Impact**: …
> Update smartelf2hex to use MemSiz instead of FileSiz

- docs/Generators/Gemmini.rst
The Gemmini config file's name is been Changed from `configs.scala` to `Configs.scala`
Updating broken links in Gemmini documentation
> Updating Gemmini.rst

- .circleci/defaults.sh
- docs/Customization/IOBinders.rst
- generators/chipyard/src/main/scala/ChipTop.scala
- generators/chipyard/src/main/scala/HarnessBinders.scala
- generators/chipyard/src/main/scala/IOBinders.scala
- generators/chipyard/src/main/scala/TestHarness.scala
- generators/chipyard/src/main/scala/config/SodorConfigs.scala
- generators/firechip/src/main/scala/BridgeBinders.scala
- generators/firechip/src/main/scala/FireSim.scala
- New `OverrideLazyIOBinder` and `ComposeLazyIOBinder` APIs to write IOBinders which modify diplomatic parameters
- Clock/reset boring replaced with ClockSinkNode auto wiring
- Fixes `make TOP=DigitalTop` and adds regression test
> Support diplomatic IOBinders

- generators/chipyard/src/main/scala/clocking/DividerOnlyClockGenerator.scala
- generators/chipyard/src/test/scala/clocking/SimplePllConfigurationSpec.scala
- generators/firechip/src/main/scala/FireSim.scala
This modifies how the reference clock is selected for the divider-only clock generator and FireSim Rational clock bridges, to produce a good result when no exact solution exists. Without introducing too much complexity, this algorithm does a brute force search over multiples of the fastest requested clock and picks the smallest that satisfies an RMS error bound. 
There a few constants here that i've mostly pulled out of thin air. The maximumAllowableFrequency is larger than you'd expect to be able to generate with typical VFOs (afaik) but was picked to work with FireSim's high tile frequencies.  
**Related issue**: #659 
> Update Reference Frequency Selection for Divider-Only Clock Generator

- .circleci/config.yml
- .circleci/defaults.sh
- generators/chipyard/src/main/scala/ConfigFragments.scala
- generators/chipyard/src/main/scala/CustomBusTopologies.scala
- generators/chipyard/src/main/scala/Subsystem.scala
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
We're still working through how we want to specify frequencies in multiclock systems -- H/T @lsteveol for shedding light on some of the current limitations. 
This PR modifies how bus clock groups are connected to better preserve the clock names presented to the top-level. This is critical since, for the foreseeable future, we are going to be relying on string matching to provide non-default frequencies. Under this change, all 5 canonical TL buses will have clocks whose names reflect the name of the bus, independent of the choice of crossing type. Here's an example:
```
dividerOnlyClockGenerator Frequency Summary
Input Reference Frequency: 8000.0 MHz                                                        
Output clock implicit_clock, requested: 800.0 MHz, actual: 800.0 MHz (division of 10) …
```
> Better Bus Frequency Specification

- generators/chipyard/src/main/scala/CustomBusTopologies.scala
Fixes a bug resulting from not RTFCing properly. Fortunately the upstream PR already does this.
**Related issue**: #713
**Impact**: rtl change 
> Fix Crossing Insertions Between Buses in Hierarchical Topology

- scripts/build-toolchains.sh
**Type of change**: new feature + bug fix
Small changes to allow Dromajo to be built with an older version of `glibc` and adding an "ignore QEMU" flag to the build toolchains script (default is to still build QEMU).
> Bump Dromajo | Optional ignore QEMU toolchain flag

- generators/chipyard/src/main/scala/ConfigFragments.scala
Surprisingly, there exists no predefined config fragment in rocketchip to set this. 
> Add config fragment for replacing L2 with broadcastManager

- scripts/init-submodules-no-riscv-tools-nolog.sh
1.8.5 is necessary for `git -C` to work.
**Related issue**: https://github.com/ucb-bar/chipyard/issues/555
**Impact**:  software change
> Update MINGIT version to 1.8.5

- build.sbt
- generators/chipyard/src/main/scala/CustomBusTopologies.scala
- generators/chipyard/src/main/scala/example/TutorialTile.scala
- generators/tracegen/src/main/scala/Tile.scala
I know that we just bumped to Chisel 3.4 in #719.  However, there have been some bugfixes in Chisel/Firrtl and feature changes in RC since the versions from November that I'd like you guys to pick up.  Starting a branch of Chipyard because there are some small fixes that need to be made across the repos.
> Bump rc chisel firrtl 3.4.1.x

- .circleci/check-commit.sh
- .circleci/config.yml
- .circleci/defaults.sh
- .circleci/do-rtl-build.sh
Small changes to improve CI a bit. First, when looking at the `check-commit` printout, split it into all 0's (valid) and all 1's (invalid, not on `master` branch) so that it is less annoying trying to find the 1 in the sea of 0's. Second, don't transfer `.git` folder on copies since we don't do `git` operations on the build server. Additionally, it adds a new SSH key to login to the build server.
> Small CI Cleanup + CI Fix

- .gitmodules
#719 changed `chisel-testers` to `ucb-bar` since there was an outstanding PR in the mainline repo (`freechipsproject`). Now that it is merged we can return to mainline (`freechipsproject`).
> Bump chisel-testers back to freechipsproject

- scripts/build-toolchains.sh
**Related issue**: #735
This permits users to specify `CC` and `CXX` for building the host software without impacting cross-compilation of libgloss-htif, same as how riscv-pk is handled.
> Disable CC and CXX overrides for libgloss build

- generators/firechip/src/main/scala/TargetConfigs.scala
**Impact**: new target config
To highlight the resource-optimizing platform configurations added to FireSim in firesim/firesim#636, a 16-core LargeBOOM configuration has been added to FireChip.
> Add 16-core LargeBOOM config to firechip

- README.md
- docs/TileLink-Diplomacy-Reference/Widgets.rst
> Docs and README update

- scripts/init-fpga.sh
- scripts/init-submodules-no-riscv-tools-nolog.sh
**Related issue**: #595
This ensures that the temporary `git config` settings for excluding certain submodules from the recursive update are properly reverted if the submodule update fails or is interrupted by SIGINT or SIGTERM.
The git commands have been refactored to loop over a centralized blacklist, which should reduce the potential for human errors when updating this script in the future.
> Ensure git config changes are reverted on failure

- generators/chipyard/src/main/scala/Clocks.scala
ChipTop reset was standardized to be async for 1.4.0
Resolves #741
> Update comment on GenerateReset

- .java_tmp/.gitignore
- variables.mk
The Java protoc plugin (part of FIRRTL) by default caches protoc in /tmp, and does not delete it afterwards.
This causes permissions failures when multiple users try to install Chipyard on the same machine, due to permissions failures over accessing the same cache in /tmp.
A solution is to place the tmpdir within the Chipyard repo. No other files besides protocjar.webcache currently use that directory, so I believe this should be safe.
> Avoid permissions conflict on shared protocjar.webcache

- generators/firechip/src/main/scala/BridgeBinders.scala
Fix WithFireSimFAME5 to allow build on FireSim non-Rocket/BOOM builds such as CVA6 or Sodor.
> WithFireSimFAME5 to allow non Rocket/BOOM build

- docs/Tools/Barstools.rst
**Type of change**: documentation fix
**Impact**: no changes to code
Fixes syntax in sentence in barstools docs describing flow
> Fixes syntax in sentence in barstools docs describing flow

- scripts/build-toolchains.sh
Remove an extra `shift` that breaks parsing of subsequent arguments.  The positional parameters are already shifted once at the end of the loop body.
> Fix parsing of --ignore-qemu option

- docs/Customization/Heterogeneous-SoCs.rst
- generators/chipyard/src/main/scala/config/HeteroConfigs.scala
**Related issue**: #786 
**Type of change**: documentation
**Impact**: documentation
Fix documentation for Heterogeneous SoCs, add documentation on hart ID ordering.
> Heterogeneous doc patches

- generators/chipyard/src/main/scala/HarnessBinders.scala
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/config/TracegenConfigs.scala
> Passing MBus clock frequency to SimDRAM

- .circleci/config.yml
**Related Issues/PRs:** https://github.com/ucb-bar/barstools/pull/98 https://github.com/ucb-bar/barstools/pull/97
**Type of change**: removing deprecated code from barstools
**Impact**: No impact except less warnings
Removed deprecated Driver code from barstools
> Bump Barstools for Deprecations Fixes

- fpga/src/main/scala/vcu118/bringup/BringupGPIOs.scala
- fpga/src/main/scala/vcu118/bringup/CustomOverlays.scala
Small modification to allow users to add pullups to Bringup GPIOs
> FPGA Prototype - Support Adding Pullup R's to Bringup GPIOs

- generators/chipyard/src/main/scala/ConfigFragments.scala
This fragment basically lets you copy the contents of the BuildRoCC key into a MultiRoCC hart mapping, so you no longer have to define custom `WithMultiRoCCX` fragments for each accelerator you want to use with MultiRoCC
> Add WithMultiRoCCFromBuildRoCC to make heterogeneous accelerator configs easier

- generators/chipyard/src/main/scala/ConfigFragments.scala
Fixes an issue where `WithTileFrequency` wouldn't modify the frequency of all tiles since clock names are based on the `TileParams` name (which defaults to `tile` and `boom_tile` for Rocket/BOOM respectively).
Tested with 2 configs:
1. `MulticlockRocketConfig`:
2. `DoubleRocketAndBoomConfig` (custom config that only used `WithTileFrequency(600)` - no other freq's changed):
> Use "tile" instead of "core" to assign freq's in WithTileFrequency config. fragment

- generators/chipyard/src/main/scala/Clocks.scala
Fixes #823 
Use IOCellKey to generate IO Cells for clock and reset
> Fix IOCell generation for clock and reset to use IOCellKey

- scripts/build-toolchains.sh
Add --arch option to build-toolchains.sh to support building other toolchain variants (e.g., rv32gc).
Add --arch option to build-toolchains.sh.
> Support specifying architecture when building tools.

- generators/chipyard/src/main/scala/Clocks.scala
This PR moves the TileResetCtrl registers to be ahead of the reset synchronizers. The TileResetCtrl registers emit an async reset that a downstream synchronizer should catch and sync.
Additionally, this gives the TileResetCtrl registers the async reset coming directly from ChipTop, through a new AsyncResetBroadcast mini network.
While in theory the ChipTop async reset can be broadcast through the same diplomacy graph as the clocks, I think that approach is a bit confusing. When we expect the async reset to be coming directly from ChipTop, the code should make it clear that that is what is happening.
> Fix TileResetCtrl to be ahead of reset synchronizers.

- generators/chipyard/src/main/scala/DigitalTop.scala
- generators/chipyard/src/main/scala/HarnessBinders.scala
- generators/chipyard/src/main/scala/IOBinders.scala
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
**Related issue**: https://github.com/ucb-bar/testchipip/pull/128
See discussion there ^
> Features for test chips

- .circleci/config.yml
- scripts/ubuntu-req.sh
This bumps the docker image to use a newer version of Git (specifically `2.31.1`). This change applies only to the `ucbbar/chipyard-ci-image:ab57b7d` for now.
https://hub.docker.com/repository/docker/ucbbar/chipyard-ci-image
> Update `git` in Docker image

- tests/charcount.c
The character count RoCC accelerator performs aligned (CacheBlockBytes) TL accesses to get input data.  However, the test application does not enforce such alignment, and the accelerator may end up processing values outside the input string.  If this happens and a ```'\0'``` is detected before the actual string starts, the accelerator sets its ```finished``` flag and returns a wrong result.
**Related issue**: #839
> Fix memory alignment in character count RoCC test

- docs/VLSI/Advanced-Usage.rst
- docs/VLSI/Tutorial.rst
- vlsi/sim.mk
Timing-annotated post-synthesis simulation targets were not configured and documentation for how to use all the sim/power targets was missing. Small clarification to ASAP7 PDK & compatible tool versions.
Added post-synthesis timing-annotated sim targets
> Timing annotated targets for post-syn sim + docs

- generators/chipyard/src/main/scala/IOBinders.scala
> Synchronize JTAG reset to JTAG.TCK.

- .circleci/config.yml
- scripts/build-toolchains.sh
- scripts/build-util.sh
Make install leaves many .o and other files laying around
Fixes problems with disk space on Github Actions runner
Reduces used disk space after toolchain build
Intermediate .o and other files are removed after building toolchain components.
Reduces disk requirements
> Runs `make clean` after `make-install` to reduce used disk

- generators/chipyard/src/main/scala/IOBinders.scala
Chisel 3.5 won't have toBool anymore.
chipsalliance/chisel3#1730
> Remove deprecatation.

- docs/Chipyard-Basics/Initial-Repo-Setup.rst
> Docker Images Comment in Docs

- common.mk
**Description**:
I frequently run Chipyard on a server with NFS-mounted hard drives (in other words, accessing files on disk is very slow), and any given `make` command usually takes upwards of 3 seconds before it even starts running. I've done a bit of profiling with `strace`, and unsurprisingly most of `make`'s time is spent on filesystem-related system calls (`stat`, `close`, etc). I didn't do extensive digging, but it looks to me like the `lookup_srcs` command in `common.mk` is the source of most of these system calls. Since that is based around `find`, I figured that trying out [`fd`](https://github.com/sharkdp/fd) might present an opportunity for optimization. Here are some benchmarking results (done with …
> Use 'fd' rather than 'find' in makefiles if available

- generators/chipyard/src/test/scala/clocking/SimplePllConfigurationSpec.scala
**Related issue**: #860 
Tested with `make -C sims/vcs launch-sbt` with `project chipyard; test`.
> Fix ScalaTest Chipyard test

- scripts/build-toolchains.sh
git.qemu.org seems to be down or under heavy load. Latest qemu
seems to have changed it's .gitmodules to use gitlab.  Since we're
using a github.com mirror, when cloning qemu use rewrite rules to
use github instead of git.qemu.org.  Also install the rewrite rules
recursively into the local config of qemu and it's submodules so
that any further git commands done interactively by the user
will also use github.
Failures to connect to git.qemu.org have caused FireSim CI to fail all day today.
> avoid git.qemu.org

- scripts/build-toolchains.sh
**Related issue**: #876 
In https://github.com/ucb-bar/chipyard/pull/876#issuecomment-831639151
it was requested that we add a note to build-toolchains.sh saying that the
url rewrites can be removed.  I went a step further and made it self-checking.
Once qemu is bumped far enough that none of it's submodules come from
git.qemu.org, then the test added in this commit will fail CI during the bump PR
and everyone will be reminded to remove the url renaming rules and change
module_build back to module_all for qemu.
> test whether git.qemu.org rewrite still needed

- .circleci/config.yml
- scripts/build-toolchains.sh
- scripts/build-util.sh
**Related issue**: #867 #868 
**Type of change**: other enhancement + bugfix
This combines all setup script-related changes and also bumps the (Ubuntu-based) Docker file used for CI (which runs the Ubuntu script for setup). This will test that at least the Ubuntu changes work and are backwards compatible with 16/18.04.
> Requirement Scripts Update

- .sbtopts
- common.mk
- project/build.properties
- variables.mk
**Related issue**: #833 
It seems like using the `.sbtopts` file helps with the thin SBT client (sets up the Chisel/Firrtl path properly). This PR changes Chipyard to be more similar to Rocket Chip and hopefully fixes #833 (or some subset of its problems). Additionally, this adds small check to make sure the `BINARY` flag is present when doing `run-*` targets.
> .sbtopts file added + Check for `BINARY/THIN_CLIENT` flags

- .circleci/config.yml
- dockerfiles/Dockerfile
- scripts/entrypoint.sh
Turns out `root` user is ideal for GitHub actions work. This PR is testing the current CI infrastructure with it.
> Use root user for the Dockerfile

- generators/chipyard/src/main/scala/DigitalTop.scala
Default generator now supports I2C and PWM periphery blocks.
> Add default support for I2C and PWM IOs.

- .circleci/check-commit.sh
- .gitmodules
- build.sbt
- scripts/tutorial-patches/build.sbt.patch
- Add submodules
- api-config-chipsalliance
- rocket-dsp-utils
- update check-commit.sh to include rocket-dsp-utils
- changes to build.sbt
- change rocket-dsptools to rocket-dp-utils
- add api-config-chipsalliance
**Type of change**: Enhancement
**Impact**: Support for additional dsp utilities
Provides access to former dsptools/rocket utilities now named ucb-bar/rocket-dsp-utils
> Integrate rocket-dsp-utils (formerly dsptools/rocket subproject)

- .circleci/config.yml
This revert the GNU toolchain in both riscv-tools and esp-tools back to it's state from the master branch (2019), since the merge into esp-gnu-toolchain has left esp-gnu-toolchain is in an unclean state in which only binutils was bumped but not the rest of the tools. A full clean bump would have also included GCC-10, which would in turn also requires more fixes including bumping buildroot and possible other regressions.
> GNU Toolchain Revert

- vlsi/example-asap7yml
Cleaning up some extraneous Hammer IR from #886
> Extraneous Hammer IR

- CHANGELOG.md
> Release Prep (changelog and firesim bump)

- common.mk
I wanted to make use of the Rocket Chip lint framework (https://github.com/chipsalliance/rocket-chip/pull/2435), and this lets users do that by setting `EXTRA_CHISEL_OPTIONS`. Here's an example of invoking the Rocket Chip lint framework:
```
$ EXTRA_CHISEL_OPTIONS="--lint * --lint-options display:*=5" make -C sims/vcs CONFIG=RocketConfig
...
[info] running chipyard.Generator
...
[info] running barstools.tapeout.transforms.GenerateTopAndHarness ...
...
[error] (run-main-0) freechips.rocketchip.linting.LintException:
[error] Lint rule anon-regs: 1 exceptions!
[error]  - Recommended fix:
[error]      Use named intermediate val, or if that fails use @chiselName or *.suggestName(...)
[error]  - Whitelist file via Chisel cmdline arg: …
```
> Add options for command-line arguments for Chisel and FIRRTL compilers

- common.mk
I'm not really sure how this ever worked before, but this `$1` needs to be escaped in `common.mk`
- Fixed awk print bug in common.mk
> Escape $1 in awk command

- fpga/Makefile
The string of path for "-ip-vivado-tcls" could be empty ("")
For example, run "make SUB_PROJECT=arty bitstream" will get errors due to the argument parsing in [prologue.tcl](https://github.com/sifive/fpga-shells/blob/d4b3878e4f5cf5c4621dbfe9b0bda1ed0dd3b995/xilinx/common/tcl/prologue.tcl) since there is no generated file like "XXX.vivado.tcl " in the working directory.
Swaping the two arguments can resolve bug.
> Swap two arguments to resolve bug

- common.mk
**Related issue**: #963 
The Verilator makefile adds a `-FI` to header files before they get filtered out. Thus, when you print by `$$1` you print each word of a line one-by-one causing parsing issues (ex. `-FI` then `<long_file>` then `-FI` then `<next_file>` etc). This fix removes the `$$1` which tells `awk` to print the entire line at once (this was the previous functionality because the make variable `$1` resolved to nothing before).
> Print entire line in `sim_files.f` for Verilator 

- docs/Prototyping/VCU118.rst
- docs/TileLink-Diplomacy-Reference/Widgets.rst
**Type of change**:  Documentation enhancement
**Impact**:  Documentation
Fixed a minor grammar bug into the VCU118 docs. `TLFragmenter` argument list referred to `holdFirstDenied` when it probably meant the `holdFirstDeny` argument.
> Fixed TLFragmenter argument list in Docs

- scripts/build-toolchains.sh
- scripts/init-submodules-no-riscv-tools-nolog.sh
Use GNU readlink on macOS, since BSD readlink doesn't work in the same way. This was resulting in the auto-generated `.sbtopts` file having the wrong contents (in the `sbt.workspace` setting).
**Impact**: script change
Fix `.sbtopts` generation on macOS
> Fix readlink on macOS

- common.mk
- docs/Advanced-Concepts/Debugging-RTL.rst
- tools/torture.mk
(Please ignore #991, that was for the wrong branch)
Running torture is really unintuitive and inconvenient, and I have to switch back and forth between the sims and torture directory.
Related issue: N/A
Type of change: other enhancement
Impact: software change
Release Notes
Add torture run option to sims makefile
> Add torture run options to makefile

- scripts/build-toolchains.sh
Currently there is no define for MAKE. Running script always throws `obsolete make version; need GNU make 4.x or later` error.
This config is from [`build-util.sh` script](https://github.com/ucb-bar/chipyard/blob/9d055fdac638ab90735cbde42fd2d86355eb260b/scripts/build-util.sh#L17-L19)
> Add define for MAKE variable

- .github/PULL_REQUEST_TEMPLATE.md
Following along with #1029, I figured we could update the PR template a bit more. Any feedback on anything that we want mentioned a PR before merging it? I added a checkbox on the `dev` branch being needed... but I feel like people might get confused with the "Impact" section?
> Update pull request template (Feedback welcome)

- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
This should improve the performance of `run-binary`, `run-asm-tests`, `run-bmark-tests`, at the expense of making the default config less tapeout-friendly. However, its expected that tapeout users will need to adjust the SerialTL settings for a chip anyways, so this is a small cost.
The FireSim configs are not affected. The SerialTL width is set to be 4, as before, so no AGFI regeneration is needed.
**Type of change**:  other enhancement
**Impact**: rtl change 
Increased default SerialTL width to 32 from 4.
> Increase default SerialTL width to 32 

- generators/chipyard/src/main/scala/config/AbstractConfig.scala
**Related issue**: Fixes #1043 
Removes duplicate `WithUARTIOCells` in the `AbstractConfig`
> Remove duplicate `WithUARTIOCells` [ci skip]

- common.mk
- variables.mk
`ENABLE_SBT_THIN_CLIENT` flag is best used with a pre-installed SBT (aka best with the SBT script). This allows you to just override the SBT binary/script with `SBT_BIN` and have the `--client` flag be handled by Chipyard's Makefile. This also adds more `make help` documentation, fixes an issue with the SBT server not being depended on, and removes unnecessary `?=`s and `override`s in `variables.mk` (this was done to properly enforce that the only way to modify the CY build system SBT is to change `SBT_BIN`).
Side note: When using the SBT script to launch things, the thin client acts nicely; properly exits on errors, displays colors, etc.
> Cleanup how to override SBT + `make help` documentation update

- variables.mk
**Related issue**: https://github.com/firesim/firesim/pull/887/files  https://github.com/firesim/firesim/issues/888
Modified from the equivalent FireSim PR:
Unfortunately, our firrtl-dependency overriding in chipyard's build.sbt has a hole wherein treadle pulls in a 1.5-SNAPSHOT from maven instead of our desired version of 1.4.1. Recently, a slew of deprecated APIs were removed in the 1.5-SNAPSHOT recently, leading treadle compilation to fail. As a result, Chipyard master and dev are broken.
Workaround this problem by specifying a FIRRTL version through the java system properties, which treadle will pick up to override the 1.5-SNAPSHOT default. We could do Chisel too. 
The right solution to this (IMO) is to just use published …
> Force FIRRTL 1.4.1

- .circleci/defaults.sh
- .github/scripts/defaults.sh
- generators/chipyard/src/main/scala/IOBinders.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
**Related issue**: None
- Fixes a bug in the MMIO port IO binder when a mem port is not present
> Fix MMIO IOBinder

- common.mk
Hide `make` warning message about `fd` not being found.
> Hide `which` warning when `fd` isn't installed

- docs/Software/index.rst
- scripts/init-software.sh
- scripts/init-submodules-no-riscv-tools-nolog.sh
nvdla-workload is very large, results in long init times. Make users initialize this explicitly (like we do with gemmini-software)
NVDLA-workload submodule is not longer initialized with init-submodules script
> Don't initialize nvdla-workload with init-submodules

- variables.mk
See ucb-bar#1079. This option ceased doing things after Java 8 (released in 2014), and openJDK considers having it included an error.
This commit is a redo of a previous one.
**Impact**: none
Removed obsolete java option.
> Remove MaxPermSize

- .github/workflows/chipyard-run-tests.yml
Current CI runs on any branch that is pushed to in the repo. This reduces the amount of CI runs to only be on pushes/PRs to `dev`, `master` and `main`.
> Run CI only on dev/master/main branches/PRs

- .github/workflows/chipyard-run-tests.yml
Since the `pull_request` CI event basically checks out the merge commit of the PR against the base branch (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) I'm deleting the `push` event CI (since that is redundant and we expect people to PR into `dev/main/master` first).
> Only run CI on pull_requests

- generators/firechip/src/test/scala/ScalaTestSuite.scala
> [firechip] Properly string interpolate exit failure in ScalaTestSuite

- variables.mk
Document simulator-timeout settings.
> Document simulator-timeout settings

- .circleci/defaults.sh
- .github/scripts/defaults.sh
- .github/scripts/run-tests.sh
- .github/workflows/chipyard-run-tests.yml
- .gitmodules
- build.sbt
- docs/Generators/fft.rst
- docs/Generators/index.rst
- generators/chipyard/src/main/scala/DigitalTop.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- tests/Makefile
- tests/fft.c
**Testing**:
Compile `fft-test.c` in the FFT Generator Repo and run it using the RocketWithFFT config. Should see close to 0 outputs for all lanes except lane 5, which should be a large, nonzero, value. 
**Status**:
FFT is receiving the passed in input but is not currently not outputting the expected values. Issue is either with the FFT or with the input points. 
MMIO-based FFT Generator.
> MMIO FFT Generator

- vlsi/Makefile
**Related issue**: #1072
- #1072 added support for FSDB with VCS. This enables it for VCS using the Hammer flow as well.
> FSDB support in VLSI flow

- vlsi/Makefile
- vlsi/power.mk
- `TestDriver` is now the top-level module in testbenches, so the scope for SAIF dumping must include `TestDriver`
- Post-P&R power analysis features are most useful with SAIFs and waveforms, so it should depend on the `sim-par-debug` target rather than just `sim-par`
- SAIF passing from simulation to power is handled automatically by Hammer, no need to include in Makefile
- Waveforms now passed to power target correctly
> Fix SAIF & Waveforms for Post-P&R Power

- generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala
This was technically correct before if the CBUS clock was the implicit clock. but this change makes it correct when that is not the case
**Impact**: rtl change 
> Have PRCI control registers be clocked by the bus they hang off of

- scripts/check-tracegen.sh
The script is written in python2 and on newer machines, `python` will default to `python3`. This fixes running `make tracegen` for me on my Fedora machine.
> tracegen: execute to axe script with python2

- .github/actions/run-tests/action.yml
- .github/scripts/check-commit.sh
- .gitmodules
This might improve clone times.
Switch to shallow clone of all submodules
> Shallow clone all submodules

- fpga/Makefile
**Related PRs / Issues **:
**Impact**:
This fixes the FPGA prototyping makefile so that it doesn't error out with "unknown option".
> Remove extra spaces in FPGA makefile

- .github/PULL_REQUEST_TEMPLATE.md
Extra space character prevents the first heading from rendering bold.
> Fix formatting typo in PR_TEMPLATE

- .github/scripts/check-commit.sh
- .github/scripts/remote-run-firesim-scala-tests.sh
- .gitmodules
- scripts/init-submodules-no-riscv-tools-nolog.sh
Reverts #1064. Shallow clones cause myriad problems,
**Impact**:
> Don't shallow clone submodules (revert #1064)

- vlsi/Makefile
Closes #1081 
Closes #1136 
**Impact**:
* ucb-bar/testchipip#141 allows users to use VCS Fine-Grained Parallelism using `-fgp` flags if they wish. This functionality is added to Hammer by default via a Synopsys plugins bump but not by default in Chipyard (should I add this in `vcs.mk` and `sims/vcs/Makefile`?)
* ucb-bar/testchipip#143 resolves a bug when `BINARY=none`.
> VCS Enhancements

- .github/workflows/chipyard-run-tests.yml
(@agebonzalez) This PR is now modified to try and fix CI for self-hosted runners. The main issue is that since we are running on self-hosted runners, self-hosted runners reuse a git clone across multiple runs (it does clean the top-level repo with `git clean -ffdx`). Normally this isn't an issue (if you have no submodules / don't change sub-submodule URLs). However, in the case that you change a sub-submodule URL (and probably other cases), you need to run a `git clean -ffdx` in all submodules recursively - which the `checkout@v2` action doesn't do. Since this is basically just deleting the clone completely, I opt for just deleting the repo contents which forces the `checkout` action to reclone the repo.
> Clean old repo contents in CI

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/chipyard-run-tests.yml
- .mergify.yml
**Impact**:
This PR is copying FireSim's automation for CI which does the following:
- Selectively run certain parts of the CI pipeline based on the files added
- If a backport request is asked, have mergify automate the backport PR (if a label called "Please Backport" is added)
- Use labels to determine what to put in a future changelog (not implemented yet, but figured it would be good to copy this)
Additionally, this PR changes a bit of the wording of the issue/PR templates (in addition to adding new fields specifying what users should do for automation).
Not necessarily part of this PR... but I created a new `1.6.x` branch which should be updated with the "Please backport" label.
> Filter CI on PR contents + Mergify support

- scripts/build-toolchains.sh
It's configure script is weird and you have to set three options to 'no' to disable
boost otherwise it will fail to configure in the presence of conda's boost.
We don't want or need the boost optional features of spike, so really disable it.
The disable I did in #1140 is enough when Boost is not installed.  However, when it is installed, you really do need to have all three options set to `no`.  Boost is now pulled in transitively when xilinx-xrt is installed into the conda environment.
I imagine that others may have run into this when using a system that had Boost installed via something other than the Firesim machine-launch-script.sh.
**Impact**:
> disable all the boosts for spike

- generators/chipyard/src/main/scala/stage/ChipyardStage.scala
With the previous list of targets some phases are reinvoked when RocketChiselStage is run, namely the convert phase, which results in double emission of each elaboration-generated FIRRTL annotation.  So I removed all of the targets that will be run by the RocketChiselStage.
**Impact**:
> Stage: avoid naming targets listed in RocketChiselStage

- generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala
> Give the PRCI widgets valnames to clean up module naming

- generators/firechip/src/main/scala/TargetConfigs.scala
> firesim: Add a config with no mem port

- CHANGELOG.md
> Update CHANGELOG.md for Chipyard release 1.7.1

- tools/dromajo/dromajo.mk
`DROMAJO_ROM `needs to point at `bootrom.rv64.img` which exists at `$(base_dir)/generators/testchipip/src/main/resources/testchipip/bootrom/bootrom.rv64.img` instead of `$(base_dir)/bootrom/bootrom.rv64.img`
**Impact**:
> DROMAJO_ROM variable fix

- generators/chipyard/src/main/scala/config/fragments/ClockingFragments.scala
This pull request fixes the frequency rounding for `DefaultClockFrequencyKey`. Before this change, setting the PBus frequency to a non integer value and using the `WithPeripheryBusFrequencyAsDefault` trait would make the default clock frequency and the PBus frequency differ when they should be the same.
**Impact**:
> Fix DefaultClockFrequencyKey rounding

- common.mk
This makes the find and fd cases match, as fd already ignores dotfiles.
The primary use case is to ignore Emacs lockfiles of the form `.#SourceFile.scala`.
**Impact**:
> Ignore dotfiles in lookup_srcs makefile function

- common.mk
FD should only find regular files in this context, and use the -e flag
This fixes the invocation of `fd` in chipyard.
- `-t f` restricts the search to regular files only
- `-e` is the standard flag for searching by file extension
**Impact**:
> Fix fd command

- .ctagsignore
Ignore parsing ctags in `.conda-env` directory.
**Impact**:
> Ignore conda-env in ctags

- variables.mk
As reported in https://github.com/sbt/sbt/issues/6468, `sbt --client` does not pass flags to the client. This causes the client to ignore `java.io.tmpdir`, which breaks Chipyard usage on a shared machine.
Revert to invoking `sbt` through `sbt-launch.jar`
**Impact**:
> Revert to using sbt-launch.jar to run SBT

- vlsi/Makefile
Without this change make buildfile Config=SmallBoomConfig fails
**Impact**:
> Remove extra parenthesis

- docs/Chipyard-Basics/Initial-Repo-Setup.rst
> Fixed typo in Initial-Repo-Setup.rst

- generators/tracegen/src/main/scala/Tile.scala
Reverts ucb-bar/chipyard#1242
My bad for merging that, we aren't up-to-date enough to use that fix yet.
> Revert "fix: S-interpolator for assert, assume and printf"

- fpga/src/main/scala/arty/TestHarness.scala
changelog: fixed Arty FPGA reset signal polarity
Fix of issue #1256
**Impact**:
> changelog: fixed TinyRocketArtyConfig FPGA reset signal polarity (Please Backport)

- .github/actions/create-conda-env/action.yml
- scripts/build-setup.sh
- scripts/build-toolchain-extra.sh
Rework of #1259 to better support non-conda users. Removes conda variables from `build-toolchain-extra.sh`. `build-setup.sh` now needs `RISCV` defined if users are skipping conda.
**Impact**:
> Remove conda from build-toolchains-extra.sh

- README.md
This fixes the path to the CY logo so that it renders properly in the README
**Impact**:
> Fix CY logo in README

- .gitignore
Using Neovim + Scala metals with Chipyard uses the following files that are auto-generated.
**Impact**:
> More files to gitignore

- generators/chipyard/src/main/scala/config/fragments/TileFragments.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
Describing some simpler configs for Rocket for testing FireSim simulation
**Impact**:
> Stripped down rocket configs for FireSim testing

- generators/firechip/src/main/scala/TargetConfigs.scala
Off of this PR: https://github.com/ucb-bar/chipyard/pull/1302, I originally tried to put these configs into firesim but I had trouble getting this to work with the build environment, so I'm just going to put these configs here for now since we seem to want them sooner rather than later. 
**Impact**:
> Add more minimal firesim configs for testing

- .github/actions/create-conda-env/action.yml
- .github/scripts/defaults.sh
- .github/scripts/run-tests.sh
- .github/workflows/chipyard-run-tests.yml
- docs/Software/Spike.rst
- generators/chipyard/src/main/resources/csrc/spiketile.cc
- generators/chipyard/src/main/resources/vsrc/spiketile.v
- generators/chipyard/src/main/scala/SpikeTile.scala
- generators/chipyard/src/main/scala/config/SpikeConfigs.scala
- generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala
- sims/common-sim-flags.mk
This PR integrates a spike processor model as a tile into chipyard.
The spike processor model supports any RISC-V ISA configuration Spike supports, and dynamically links with spike-as-a-library.
The spike processor interfaces with chipyard through a cache-coherent Tilelink model.
Of course, this shouldn't be used for any performance-modelling.
It is useful for stress-testing MMIO devices, or accelerators.
Adding RoCC support would be a cool extension.
Also, atomics aren't guaranteed to be atomic.
TODO:
**Impact**:
> Spike-as-a-Tile

- .github/scripts/defaults.sh
- generators/chipyard/src/main/scala/Subsystem.scala
- generators/chipyard/src/main/scala/config/BoomConfigs.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
Rocket-chip now supports "cloning" lazy modules. The primary use-case is to "clone" duplicated tiles, instead of re-elaborating the Chisel for each tile.
This PR adds example configs `Cloned64RocketConfig` and `Cloned64MegaBoomConfig` to demonstrate this features.
`Cloned64MegaBoomConfig` can compile a VCS simulator in < 15 minutes.
**Impact**:
> Add clone-tile configs

- generators/chipyard/src/main/scala/config/NoCConfigs.scala
A sbus-only ring NoC is a nice simple design-point for basic NoC-based architectures. 
**Impact**:
> Add example ring-only NoC Config

- common.mk
- Uses order only prereqs to build the output dir (https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html). Avoids extra simulation runs.
- Adds `firstword` to the hex-ification rule in `run-binary-hex` to avoid bugs in the case where `BINARY='bin arg1 arg2'`. Otherwise the hex-ficiation rule will be given the args as well.
**Impact**:
> Makefile bug fixes

- .github/scripts/defaults.sh
- generators/chipyard/src/main/scala/Subsystem.scala
- generators/chipyard/src/main/scala/clocking/TileResetSetter.scala
- generators/chipyard/src/main/scala/config/NoCoreConfigs.scala
- generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala
This is useful for testing  Requires a very minor rocket-chip bump
**Impact**:
> Add a config with no cores

- docs/Advanced-Concepts/Chip-Communication.rst
- docs/Customization/DMA-Devices.rst
- docs/Customization/Dsptools-Blocks.rst
- docs/Customization/Incorporating-Verilog-Blocks.rst
- docs/Customization/Keys-Traits-Configs.rst
- docs/Customization/MMIO-Peripherals.rst
- docs/Customization/Memory-Hierarchy.rst
- docs/Customization/NoC-SoCs.rst
- docs/Generators/SiFive-Generators.rst
- docs/Generators/fft.rst
- generators/chipyard/src/main/scala/config/BoomConfigs.scala
- generators/chipyard/src/main/scala/config/MMIOAcceleratorConfigs.scala
- generators/chipyard/src/main/scala/config/PeripheralDeviceConfigs.scala
- generators/chipyard/src/main/scala/config/RoCCAcceleratorConfigs.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
Sample configs have been getting dumped into RocketConfigs. This PR splits up that file into RoCCAccelConfigs/MMIOAccelConfigs/PeripheralDeviceConfigs, to improve discoverability of features.
**Impact**:
> Split up RocketConfigs.scala

- variables.mk
This is what 99% of users will want if they override `MODEL`.
**Impact**:
> Set VLOG_MODEL=MODEL by default in variables.mk

- common.mk
- fpga/Makefile
- sims/common-sim-flags.mk
- sims/vcs/Makefile
- sims/verilator/Makefile
- variables.mk
- vcs.mk
- vlsi/Makefile
This PR addresses #1341.
Removes $(OUT_DIR) which is `gen-collateral` when re-compiling.
**Impact**:
> Remove gen-collateral when rebuilding

- vlsi/Makefile
- vlsi/power.mk
- vlsi/sim.mk
This makes the expansion of "cat $(VLSI_RTL)" happen as a child of the shell that runs the for loop.
The existing version will sometimes produce a bash "too many arguments" error because the 
$(shell cat $(VLSI_RTL)) 
is expanded first and then passed as a giant command to bash.
**Impact**:
> Fix VLSI input files list emission to avoid bash "too many arguments" error

- common.mk
- fpga/Makefile
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- project/build.properties
- sims/common-sim-flags.mk
- vlsi/Makefile
- Bump to SBT 1.8.2 (doesn't break anything but adds deprecation warnings)
- Have the `EICG_wrapper.v` be added by the FIRRTL `addResource/Path` call instead of manually copied. This requires adding a new config. fragment.
- Add a missing `"` to fix the `make help` formatting be correct
- Added in the VLSI `Makefile` a `.PHONY: all` to satisfy the `pre-commit` `Makefile` syntax check
**Impact**:
> Small build system improvements

- .github/scripts/run-tests.sh
This improves performance of CI further, the big noc-config CI takes a long time to run.
**Impact**:
> Reduce test cases for noc-config in CI

- docs/VLSI/Advanced-Usage.rst
- docs/VLSI/Basic-Flow.rst
- vlsi/power.mk
This fixes a small bug with the hierarchical VLSI flow for power-par and adds clarifying documentation nothing that hierarchical flows must be cognizant about overriding `VLSI_TOP`.
@bdngo @moresa75
**Impact**:
> Fix & clarify hierarchical flows

- build.sbt
- docs/Customization/DMA-Devices.rst
- docs/TileLink-Diplomacy-Reference/NodeTypes.rst
- generators/chipyard/src/main/scala/example/InitZero.scala
- generators/chipyard/src/main/scala/example/NodeTypes.scala
- scripts/tutorial-patches/build.sbt.patch
TLHelper 1) obfuscates the underlying node architecture and 2) results in otherwise unnecessary dependencies on testchipip
**Impact**:
> Remove TLHelper, directly use tilelink node constructors

- docs/VLSI/Advanced-Usage.rst
- scripts/upgrade-vlsi.sh
`upgrade-vlsi.sh` takes args to pattern match specific plugin names. Recommend to do this instead of upgrading all plugins + Hammer at once, since incompatibility issues can arise in the latter case.
@moresa75
**Impact**:
> Better VLSI upgrade script

- generators/chipyard/src/main/scala/stage/ChipyardAnnotations.scala
Taken from #872. Updates the assertion message if multiple configs concatenated cannot be split.
**Impact**:
> Update assert message if configs can't be split by `:`

- common.mk
- variables.mk
> Remove Duplicate Compiler Flags

- .github/scripts/check-commit.sh
- .gitmodules
- docs/Tools/Chisel-Testers.rst
- docs/Tools/index.rst
Since this is managed by SBT/maven now, we shouldn't need this submodule.
**Impact**:
> Remove chisel-testers submodule

- .github/workflows/chipyard-full-flow.yml
- common.mk
- docs/Customization/Keys-Traits-Configs.rst
- scripts/config-finder.py
Adds a new target to help users find *some* config fragments (also adds to the docs on how to use it).
Unfortunately, I wanted to do this through Scala reflection, however, that isn't possible since you can only look at the subclasses of `sealed` traits/classes. This is a simple solution that covers large majority of configs (assuming config. fragments are defined on a single line - "class NAME extends CONFIG\n"). This doesn't cover configs that don't inherit directly from `Config`... I don't have time to do that right now (or figure out a better way).
TODO:
**Impact**:
> Config finder `make` target

- docs/Simulation/Software-RTL-Simulation.rst
> Add graphml visualization section to docs

- common.mk
- scripts/check-tracegen.sh
Same as #1381 but for some other `/tmp/` files/directories. 
**Impact**:
> Move more tmp/ folders to a unique location

- conda-reqs/chipyard.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
This sync's FireSim's conda environment with Chipyard and at the same time unpins Chipyard dependencies. This should help the solver resolve more often and faster.
**Impact**:
> Match CY/FireSim deps | Unpin deps | Update lockfiles

- vlsi/Makefile
- vlsi/sim.mk
In #1324 I consolidated the input files for simulation, but broke post-syn/par simulation as a result.
This PR makes sure that no TOP Verilog files make it to post-syn/par sims.
Being tested by @bdngo
@moresa75
**Impact**:
> Fix post-syn/par sim

- conda-reqs/chipyard.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
- conda-reqs/riscv-tools.yaml
- generators/chipyard/src/main/scala/config/RoCCAcceleratorConfigs.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
> Remove e2fsprogs | Bump RV toolchain

- .readthedocs.yml
We only test that the HTML version of the docs compiles so we should have the ReadTheDocs website only generate HTML.
**Impact**:
> Only support HTML docs

- common.mk
- generators/chipyard/src/main/resources/csrc/cospike.cc
- generators/chipyard/src/main/resources/csrc/spiketile.cc
- scripts/build-toolchain-extra.sh
- Fixes issue where if you updated a Verilog file, the `SFC_LEVEL` would be not set breaking the flow. Done by moving the `VLOG_SOURCES` as a prereq of `SFC_LEVEL`.
- Adds new `ibex.mk` so that if a Ibex file is updated it would elaborate the SoC again (which would preprocess the Verilog sources)
- Ignores `mv` `stderr` output (the error code is ignored anyways by using `-`)
- #1386 never passed CI. This fixes 2 errors with the PR, not init'ing the DramSim submodule and changing the `int` to `size_t` in `cospike/spiketile.cc` so that GCC can detect that the `cfg_t` constructor is valid.
Requires review on https://github.com/ucb-bar/ibex-wrapper/pull/5
**Impact**:
> Fix Verilog Prerequisites + Ignore `mv` stdout

- variables.mk
When redirecting SBT to a pipe (for tee), ANSI color is suppressed unless color=always is set.
Fixes bug introduced by #1400 
**Impact**:
> Fix ANSI color output

- common.mk
Fixes bug introduced by #1400 
**Impact**:
> Fix chisel elab errors not causing flow to stop

- .github/scripts/check-commit.sh
- .gitmodules
- conda-reqs/chipyard.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
- conda-reqs/esp-tools.yaml
- conda-reqs/riscv-tools.yaml
- docs/VLSI/ASAP7-Tutorial.rst
- docs/VLSI/Basic-Flow.rst
- docs/VLSI/Hammer.rst
- docs/VLSI/Sky130-Commercial-Tutorial.rst
- scripts/init-submodules-no-riscv-tools-nolog.sh
- scripts/init-vlsi.sh
ucb-bar/hammer#713 moved the (now public) Cadence & Synopsys plugins into the main Hammer repository and published package.
Also moved `litex-hub` channel priority lower to resolve conda package issues I was having after #1392.
**Impact**:
> Remove Cadence & Synopsys plugins

- CHANGELOG.md
> Bump FireSim

- .github/scripts/check-commit.sh
- .github/workflows/chipyard-run-tests.yml
- docs/Software/Spike.rst
- generators/chipyard/src/main/resources/csrc/spiketile.cc
- generators/chipyard/src/main/resources/vsrc/spiketile.v
- generators/chipyard/src/main/scala/SpikeTile.scala
- generators/chipyard/src/main/scala/Subsystem.scala
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/config/SpikeConfigs.scala
- tests/Makefile
- tests/hello.c
- Support for TightlyCoupledMemory (TCM) in the Spike model, allowing for fast Linux boot with RTL simulation of the uncore with the SpikeUltraFastConfig
- Add new "chosen" node to DTS, to request earlycon be with the sifive uart.
- Add hello-world bare-metal program
- Fix BOOM marchid
- Fix icenet/rocc issues with default marshal kernel
- Re-add password login
TODO:
**Impact**:
> Various improvements and fixes

- .github/actions/cleanup-conda/action.yml
See title. With the addition of new conda environments in our CI that don't match the naming scheme: `cy-<date>-<hash>-<riscv/esp>-tools` the conda cleanup script can fail blocking CI since it greedly matches any numeric character in the conda env. This fixes that issue.
**Impact**:
> Ensure conda cleanup regex properly filters out non-numeric chars

- generators/chipyard/src/main/scala/ConfigFinder.scala
- generators/chipyard/src/main/scala/example/CustomChipTop.scala
#1411 broke main with some merge conflicts. This fixes them
**Impact**:
> Resolve merge conflicts in chisel3.5.6 bump

- tests/Makefile
changelog:omit
Minor change. Added the complete variable definition of the `riscv64-unknown-elf-` toolchain. Added the `ARCH` and `ABI` flags definitions.
The default compilation flow is not affected.
**Impact**:
> ADD: improve Makefile in tests/, add explicit arch flags

- generators/chipyard/src/main/scala/config/ChipConfigs.scala
Previously, a special config fragment was necessary to prevent the chip from generating serial_tl packets during reset. Additionally, this was done using AsyncQueues, instead of just BlockDuringReset.
This changes all designs to block serial_tl while under reset
**Impact**:
> Bump TestChipIp to improve default serial_tl behavior

- tests/Makefile
- tests/encoding.h
- tests/hello.c
- tests/marchid.h
- tests/mt-hello.c
Demo of some simple bare-metal code which runs hello-world on each core. @jzhou1318 
**Impact**:
> Add mt-helloworld example

- software/tutorial/.gitignore
- software/tutorial/build.sh
- software/tutorial/marshal-configs/mobilenet-baremetal.yaml
- software/tutorial/marshal-configs/resnet50-baremetal.yaml
- software/tutorial/marshal-configs/resnet50-linux-interactive.yaml
- software/tutorial/marshal-configs/resnet50-linux.yaml
> Add tutorial software

- generators/chipyard/src/main/resources/csrc/cospike.cc
> misc: many fixes to cospike

- conda-reqs/chipyard.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
Bump to Hammer 1.1.1
**Impact**:
> Bump to Hammer 1.1.1

- generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala
- generators/chipyard/src/main/scala/clocking/TileClockGater.scala
Configs which disable those settings will prevent these blocks from appearing at all, instead of generating a no-op block.
**Impact**:
> Support not instantiating the TileClockGater/ResetSetter PRCI control

- docs/Advanced-Concepts/Chip-Communication.rst
- docs/Prototyping/VCU118.rst
- fpga/src/main/scala/arty100t/HarnessBinders.scala
- generators/chipyard/src/main/scala/HarnessBinders.scala
- generators/chipyard/src/main/scala/config/ChipConfigs.scala
- generators/chipyard/src/main/scala/example/FlatTestHarness.scala
- generators/firechip/src/main/scala/BridgeBinders.scala
Previously, the serial_tl_clock is generated on-chip, and passed to the host bringup FPGA. This flips that, so the FPGA must generate the clock.
Follows up on #1435 to improve the serial_tl robustness and ease-of-use.
**Impact**:
> Flip serial_tl_clock to be generated off-chip

- generators/chipyard/src/main/scala/DigitalTop.scala
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
Previously, the BootAddrReg device is always instantiated on all designs.
This change makes that device optional, so it can be removed from designs with no tiles.
This also adds the config flag for CustomBootPin to AbstractConfig, so its clearer what the set of "default devices" includes.
**Impact**:
> Make BootAddrReg optional

- common.mk
- generators/chipyard/src/main/resources/csrc/cospike.cc
> Generate objdump | check BINARY | cospike fixes

- .github/scripts/run-tests.sh
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/config/ChipConfigs.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- generators/chipyard/src/main/scala/config/SodorConfigs.scala
- generators/chipyard/src/main/scala/config/SpikeConfigs.scala
- generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala
- generators/chipyard/src/main/scala/example/FlatTestHarness.scala
- generators/chipyard/src/main/scala/harness/HarnessBinders.scala
- generators/firechip/src/main/scala/BridgeBinders.scala
This change fixes support for configs in which the TLSerdesser is unidirectional; that is, cases in which the chip acts as only the manager, and off chip acts as only the client.
This simplifies the memory map for all default designs as we no longer have to add a stub off-chip memory to provide the chip-client/harness-manager link.
Why not use the existing `TLDesser/TLSerder`, which already do this? Those IMO can be deleted as their implementations are now supported by the generalized `TLSerdesser`.
Since we support configs now where the serializer only acts as a client to the FBus, a bunch of `WithSerialPBusMem` fragments can be removed, as these were used to specify where the stub tilelink device sat.
**Impact**:
> Support uni-directional TLSerdesser

- .github/scripts/defaults.sh
- .github/scripts/run-tests.sh
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/config/PeripheralDeviceConfigs.scala
Add some tests to CI to provide coverage that was lost when changing default back to single-channel.
**Impact**:
> Set default config back to 1-channel

- sims/xcelium/Makefile
Replaces the target names with `$@` and also replaces `$(base_dir)/.conda-env` with `$CONDA_PREFIX` since that is more robust under FS-as-top.
**Impact**:
> Small QOL fixes for Xcelium

- fpga/src/main/scala/vcu118/TestHarness.scala
When evaluating a RV32 design(just add `WithRV32 `in the `RocketVCU118Config`) on vcu118. The beatBytes is 4, and therefore `dataBits `of the MemoryBus will be 32. However the AXI that goes to MIG core is predefined as 64bits wide. Therefore, there is a data field width mismatch here, causing the RV32 design can not access DDR4 of VCU118 successfully. See WithDDRMem HarnessBinder for vcu118 below: 
```
class WithDDRMem extends OverrideHarnessBinder({
(system: CanHaveMasterTLMemPort, th: BaseModule with HasHarnessSignalReferences, ports: Seq[HeterogeneousBag[TLBundle]]) => {
th match { case vcu118th: VCU118FPGATestHarnessImp => {
require(ports.size == 1)
println(s"the ddr port ${ports}")
val bundles = vcu118th.vcu118Outer.ddrClient.out.map(_._1)
println(s"the val bundles = …
```
> (VCU118 DDR HarnessBinder)Fix data field width mismatch between DDR AXI and TileLink MemoryBus 

- .github/workflows/chipyard-full-flow.yml
- generators/chipyard/src/main/scala/clocking/ClockBinders.scala
- generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala
- generators/chipyard/src/main/scala/clocking/TLClockDivider.scala
- generators/chipyard/src/main/scala/clocking/TileClockGater.scala
- generators/chipyard/src/main/scala/clocking/TileResetSetter.scala
**Localizes all the clock devices to prci_ctrl_domain, and adds a xbar for all the clock control devices.**
This should improve physical design of clock/reset devices, since it all is under a single module hierarchically with fewer IO
**Fixes TLClockDivider behavior.**
Previously, if the divisor register somehow misses the reset pulse, it would set the DividerOrPass to a bad state that could initialize the system to a very slow clock. This would never happen in a physical implementation. 
However, in RTL simulations where the power-reset sequence is not totally simulated, only a `negedge reset` might be evaluated with no `posedge reset`. Since the AsyncResetRegs are sensitive to `posedge reset or posedge clock`, and the `asyncReset` may deassert before a clock arrives at the TLBus, that …
> Improvements to chipyard clocking

- .github/scripts/install-conda.sh
- conda-reqs/chipyard.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
- conda-reqs/esp-tools.yaml
- conda-reqs/riscv-tools.yaml
- docs/Chipyard-Basics/Initial-Repo-Setup.rst
Force `conda-lock` to `1.4.*` versions (sometimes a lower `1.*` version would error). Use `==` for specific `X.Y.Z` versions and use `=` for looser `X.Y.*` versions. Bump `install-conda.sh` script (even though it isn't used outside of the Dockerfile which hasn't been updated in a while).
**Impact**:
> Loosen/tighten conda requirements | Fix conda-lock req

- common.mk
- variables.mk
Fixes issue where if the compilation was stopped (i.e CTRL-C'ed during the `firtool` recipe) it would fail to update any transient make variable (since the old `$(SFC_LEVEL) $(EXTRA_FIRRTL_OPTIONS) $(FINAL_ANNO_FILE) $(MFC_LOWERING_OPTIONS)` recipe would not be re-run). Instead of transiently updating variables, instead store the results to a file so that make can properly track what variables updated.
Always try to dump with sources inlined for any of the `run-*` targets.
Sometimes when SBT assembly is run and the `*.jar` it is supposed to change/generate is cached/up-to-date it will not touch the output `*.jar` file. Therefore force touch it so that it is updated for future make requirements. 
**Impact**:
> Misc Makefile Fixes

- common.mk
Ignore running sbt assembly for barstools if the sources for it haven't changed. Also moves the verilog dependency to it's original location (running the FIRRTL compiler depends on the verilog sources)
**Impact**:
> Ignore barstools compilation if not needed

- generators/chipyard/src/main/scala/config/NoCConfigs.scala
NoC node mapping needs to be updated to match the new PRCI bus organization.
**Impact**:
> Update NoC example config to match new PRCI organization

- .github/scripts/check-commit.sh
- .github/scripts/defaults.sh
- .github/scripts/run-tests.sh
- .github/workflows/chipyard-run-tests.yml
- .gitmodules
- build.sbt
- docs/Generators/Prefetchers.rst
- docs/Generators/index.rst
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- generators/chipyard/src/main/scala/config/fragments/TileFragments.scala
- scripts/tutorial-patches/build.sbt.patch
BARF (BAR-fetchers) is a generic API for describing simple prefetchers, that can be instantiated in front of L1 HellaCaches, or in TileLink bus widgets.
Currently, a handful of example algorithms are implemented.
**Impact**:
> Integrate barf (prefetchers)

- docs/Customization/RoCC-Accelerators.rst
Small PR based on feedback from EE194 (tapeout) to explain what RoCC is at a higher level, and some resources for actually using the RoCC interface.
**Impact**:
> Add higher level explanations of RoCC + more resources

- generators/chipyard/src/main/scala/DigitalTop.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
This generalized the backing-scratchpad feature in testchipip to support - 
- Placing the spad at arbitrary buses
- Banking the scratchpad by cacheline
- Placing multiple scratchpads on the bus, this allows for construction of scratchpad "partitions"
**Impact**:
> Support banked/partitioned scratchpads

- .github/scripts/check-commit.sh
- .github/scripts/defaults.sh
- .github/scripts/run-tests.sh
- .github/workflows/chipyard-run-tests.yml
- .gitmodules
- build.sbt
- docs/Generators/Shuttle.rst
- docs/Generators/index.rst
- generators/chipyard/src/main/resources/csrc/cospike.cc
- generators/chipyard/src/main/scala/config/ShuttleConfigs.scala
- scripts/tutorial-patches/build.sbt.patch
This PR also includes a bunch of changes to make cosim more robust.
**Impact**:
> Add dual-issue in-order "shuttle" core

- vlsi/example-asap7.yml
- vlsi/example-design.yml
- vlsi/example-designs/sky130-commercial.yml
- vlsi/example-designs/sky130-openroad-rockettile.yml
- vlsi/example-designs/sky130-openroad.yml
- vlsi/example-designs/sky130-rocket.yml
- vlsi/example-sky130.yml
- vlsi/sim.mk
The clock name for TinyRocketConfig has changed from `clock_clock` to `clock_uncore_clock`.
Also the Make variable `PREPROC_DEFINES` was renamed to `SIM_PREPROC_DEFINES`, so Hammer was breaking because the sim.defines YAML key was being set to nothing.
Pulling these changes from #1514 so it's easier to merge for the release.
**Impact**:
> VLSI Fixes

- docs/Customization/Memory-Hierarchy.rst
`WithBackingScratchpad` is removed on [testchipip #3497d53](https://github.com/ucb-bar/testchipip/commit/3497d538f3fae4b0cc4db6ee9c19f289f7fa37aa). Users should use `WithScratchpad(base, size, banks, partitions, busWhere)` instead.
**Impact**:
> FIX: fixing docs, WithBackingScratchpad is deprecated, use WithScratchpad instead

- docs/Advanced-Concepts/CDEs.rst
N/A
**Impact**:
The code snippets, as written, don't work when you paste them into a Scala file and run it, due to missing `)` and that there is no singleton `Config` object. I also think it's worth including on this page the way that config fragments toward the bottom/right get overridden by fragments on the left/top.
> Fixed typos in CDE docs page, and added info on how config fragments in the chain can be overridden

- docs/VLSI/ASAP7-Tutorial.rst
Add an explicit statement that the ASAP7 Tutorial flow should be executed in the `vlsi` directory.
**Impact**:
> Docs add that ASAP7 tutorial should be executed in vlsi directory

- docs/Chipyard-Basics/Initial-Repo-Setup.rst
Add a comment on the docs that users may want to skip the firemarshal/firesim components if they are only using chipyard for RTL-dev/VLSI flows
ERROR: Failed to build workload br-base.json when running `build-setup.sh` on BWRC server.
**Impact**:
> ADD: add documentation for build-setup skip

- .github/workflows/config/release-notes.json
- .github/workflows/release-notes.yml
- .github/workflows/require-label.yml
- .mergify.yml
Follows the same type of automation done by https://github.com/chipsalliance/chisel/pull/3170. Note: This doesn't append to the `CHANGELOG.md` file.
**Impact**:
> Add release note automation

- .gitignore
- generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
- tests/spiflash.h
This reapplies #1511, while also keeping the default parameter order for `WithUART`/`WithSPIFlash`, so legacy configs which use those fragments will maintain the same behavior.
Do not merge until after 1.10.0
**Impact**:
> Improve peripheral config binders (Reapply #1511)

- .github/scripts/remote-run-firesim-scala-tests.sh
- .github/workflows/chipyard-full-flow.yml
- .github/workflows/chipyard-run-tests.yml
Use new CI machines. Explicitly disable Vivado FireSim tests since the CI machine also has Vivado installed on it (same functionality as before). Also ensure that `JAVA_TMP_DIR` is deleted on cleanup.
**Impact**:
> Use new CI machines

- .github/actions/create-conda-env/action.yml
- .github/scripts/install-conda.sh
- conda-reqs/chipyard.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
- docs/Chipyard-Basics/Initial-Repo-Setup.rst
- scripts/build-setup.sh
- scripts/generate-conda-lockfiles.sh
Testing the following theory:
`conda-lock` under the hood uses `conda` to solve some extra dependencies that are machine-specific in addition to the pre-computed lockfile dependencies. When it does this it uses a non-optimized version (i.e. without libmamba solver) of `conda` which is very slow for many dependencies. This PR forces `conda-lock` to use the `conda` that the user has installed (by doing `which conda` and passing that).
This also bumps the lockfiles, makes the default instructions include installing `libmamba`, and uses the most recent conda version in CI.
**Impact**:
> Bump lockfiles | Force user-installed conda during conda-lock

- build.sbt
- common.mk
- docs/VLSI/Advanced-Usage.rst
- generators/chipyard/src/main/scala/harness/TestHarness.scala
- generators/chipyard/src/main/scala/upf/ChipTopUPF.scala
- generators/chipyard/src/main/scala/upf/UPFAspect.scala
- generators/chipyard/src/main/scala/upf/UPFGen.scala
- generators/chipyard/src/main/scala/upf/UPFInputs.scala
UPF Generation working on current chipyard. Current UPFInputs are based on a 2 core RocketConfig. Using a noop annotation to satisfy requirements for toAnnotation in UPFAspect. 
**Impact**:
> UPF Generation

- generators/chipyard/src/main/resources/csrc/cospike.cc
- generators/chipyard/src/main/resources/vsrc/cospike.v
- generators/chipyard/src/main/scala/Cospike.scala
- generators/chipyard/src/main/scala/harness/HarnessBinders.scala
> Bump spike | support M-mode only cosim

- generators/chipyard/src/main/scala/clocking/ClockBinders.scala
- generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala
Fragmenter infront of FIFO-fixer needs to track way too many source-Ids
**Impact**:
> Fix FIFO-fixing for PRCI bus

- docs/Chipyard-Basics/Initial-Repo-Setup.rst
**Impact**:
I don't believe this PR needs to be included on the changelog, as it's an extremely minor documentation tweak.
> Documentation: Change "don't use Windows" to "if using Windows, use WSL"

- docs/Advanced-Concepts/Chip-Communication.rst
- generators/chipyard/src/main/scala/config/ChipConfigs.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- generators/chipyard/src/main/scala/example/FlatTestHarness.scala
- generators/chipyard/src/main/scala/harness/HarnessBinders.scala
- generators/firechip/src/main/scala/BridgeBinders.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
Previously, the MultiClockHarnessAXIMem stuff attached SimDRAM over the serial-tl link. This was done to enable test-chip-like simulations, where the HarnessBinder/BridgeBinder would effectively implement a similar system as what would go on the bringup platform.
Now that multi-chip-tops are supported, and co-simulation of the ChipTop and the BringupTop are supported, we can remove all this old Harness-level stuff to reduce duplication, and to simplify future development of serial-tl-connected systems.
**Impact**:
> Remove MultiClockHarnessAXIMem

- .github/scripts/defaults.sh
- fpga/src/main/scala/arty100t/Harness.scala
Requires minor bump of fpga-shells, rocket-chip
**Impact**:
> Fix Arty100T verilog build

- scripts/insert-includes.py
This fixes CI for CVA6/nvdla on a system that does not have a /usr/bin/python interpreter by making the script use one from conda env.
Before, CI for prepare-chipyard-cores and prepare-chipyard-accel would fail on this particular system when building cva6 and nvdla that uses this script:
```
make[1]: /scratch/buildbot/actions-runner/_work/chipyard/chipyard/scripts/insert-includes.py: No such file or directory
/scratch/buildbot/actions-runner/_work/chipyard/chipyard/scripts/insert-includes.py combined.sv /scratch/buildbot/actions-runner/_work/chipyard/chipyard/generators/cva6/src/main/resources/cva6/vsrc/CVA6CoreBlackbox.preprocessed.sv /scratch/buildbot/actions-runner/_work/chipyard/chipyard/generators/cva6/src/main/resources/cva6/vsrc/cva6/src/fpga-support/behav/common/include …
```
> Make scripts/insert-includes.py use Python from conda env

- generators/chipyard/src/main/scala/harness/HarnessBinders.scala
`Pipe` in https://github.com/firesim/icenet/blob/bbce029e3d3e4b11578f380ad48012fc49247d60/src/main/scala/NIC.scala#L603 is set on a different clock & reset domain than external ports of the NIC, causing the `nic-loopback` test to fail.
This PR fixes this by explicitly setting the clock & reset domain in the testharness for NIC loopbacks.
Related PR
- https://github.com/firesim/icenet/pull/40
**Impact**:
> Fix icenet-loopback clock and reset domain

- vlsi/tutorial.mk
Previously, this unintuitively overrode the `INPUT_CONFS` in `vlsi/Makefile` in all cases.
**Impact**:
> [vlsi][ci skip] Fix tutorial.mk so that INPUT_CONFS override only affects tutorials

- generators/chipyard/src/main/scala/config/fragments/TileFragments.scala
For configs with wide SBUS, a narrow rocket cache is easier to PD, and does not incur any performance loss usually
**Impact**:
> Add NarrowRocketCache config fragment

- scripts/uniquify-module-names.py
When there is a module that is uniquified between the model and top, the regex in this file will improperly over-rename things. Ex: `MemLoader` is renamed to `MemLoader_UNIQUE`... however `ReverseMemLoader` would also be renamed. This PR fixes this issue by fixing the regex and adding more capture groups to properly capture spaces.
Fixes #1624 
**Impact**:
> Fix regex for similar module names that are uniquified

- docs/Simulation/Software-RTL-Simulation.rst
The most important part of this addition, IMO, is the note about `__main()`, since it's currently not noted anywhere in Chipyard's docs. It was initially very hard for me to find any explanation about `__main` until I stumbled across libgloss-htif's readme page.
@ maintainers: I don't actually know for sure if libgloss-htif is the right place to link to. It's the only documentation I could find that includes an explanation on `__main`, but I don't know if that's actually the code used for Verilator/VCS simulations.
**Impact**:
- [N/A] Did you delete any extraneous prints/debugging code?
- [N/A, no permissions] Did you mark the PR with a `changelog:` label?
- [N/A] (If applicable) Did you update the conda …
> docs: Add info on chipyard's tests directory and how to do multithreading in RTL simulations

- common.mk
- conda-reqs/chipyard.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
- docs/Customization/Incorporating-Verilog-Blocks.rst
- generators/chipyard/src/main/scala/example/GCD.scala
- scripts/generate-conda-lockfiles.sh
- scripts/insert-includes.py
- tests/gcd.c
- Moves Verilog make dependencies up to `jar` generation so that Verilog files are properly updated in the `jar`. This was bugged before since you would have to recompile Scala sources to see the Verilog sources change.
- Adds documentation on some of the corner cases of adding blackboxes
- Updates insert includes script to be recursive (if an `include` has `include` within it, rerun the replacement)
- Bump firtool to 1.58.0
- Updates the `generate-conda-lockfiles` script to delete the lockfile before regenerating (fixes issue where `conda-lock` would get stuck regenerating the lockfile if the lockfile pre-existed)
- Moves GCD to avoid 0x1000 (same address as bootrom)
It also exposes a bug mentioned here: https://github.com/ucb-bar/chipyard/issues/1624#issuecomment-1780183452. This is an …
> Rebuild `jar`s when `sv`/`v` files are changed + Add documentation on blackboxes

- .github/workflows/chipyard-run-tests.yml
With the addition of new CI machines the old `self-hosted` label includes those new machines breaking CI. CI only expects to run on `jkt*` machines. A new label was added for these machines called `old-ci` that only covers those machines. CI is now switched to this label.
**Impact**:
> Run only on old-ci machines

- .github/workflows/chipyard-full-flow.yml
- .github/workflows/chipyard-run-tests.yml
Updates the CI labels to use the new CI machine (`as4`). There are 8 runners on that single machine instead of 12 spread over 2.
**Impact**:
> Update to use the new CI machines

- tests/Makefile
- tests/libgloss.mk
**Issue:** In `/tests`, when building libgloss locally, i.e., with `BUILD_LIBGLOSS=1`, `libgloss.mk` expects the variable `TARGET` to be defined. It uses `--host=$(TARGET)` for GCC cross-compilation. Currently, this errors out.
**Fix:** Set `TARGET` in `tests/Makefile`. Replace the use of `PREFIX` with `TARGET` so we only have a single source of truth.
**Impact**:
> Use TARGET instead of PREFIX in /tests Makefile(s)

- .github/scripts/check-commit.sh
- .github/scripts/defaults.sh
- .gitmodules
- build.sbt
- generators/chipyard/src/main/scala/config/RoCCAcceleratorConfigs.scala
- scripts/insert-includes.py
- scripts/tutorial-patches/build.sbt.patch
Adds https://github.com/chipsalliance/Caliptra 's AES 256 ECB cryptography core as a RoCC accelerator. Also adds a repo to help users create RoCC memory streaming accelerators (i.e. extend the classes/traits to quickly create a streaming accel). 
**Impact**:
> Add Caliptra AES256 ECB engine as RoCC accelerator

- generators/chipyard/src/main/scala/iobinders/IOBinders.scala
`cloneType` is a Chisel-internal method; use `chiselTypeOf` to construct an IO of the same type and direction.
`cloneType` appears to strip the `Flipped` modifier from types, so attempting to instantiate a bringup host config with a serial-TL clock driven by the DUT results in a connection failure during elaboration since both the ChipTop IO and the DigitalTop port are drivers.
**Impact**:
> Fix IO direction for host Serial-TL port

- .github/workflows/chipyard-full-flow.yml
- conda-reqs/chipyard.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
- docs/VLSI/Sky130-Commercial-Tutorial.rst
- docs/VLSI/Sky130-OpenROAD-Tutorial.rst
- vlsi/Makefile
- vlsi/sim.mk
Bumped Hammer to 1.2.0, ChipTop DUT was renamed chiptop -> chiptop0, and added FSDB=1 flag when we dump FSDB waveform (otherwise RTL sim errors).
**Impact**:
> Hammer bump and minor VLSI fixes

- generators/firechip/src/main/scala/TargetConfigs.scala
Small comment fix. On FireSim with F1 instances we support 64GBs of DRAM.
**Impact**:
> Update TargetConfigs.scala for 64G comment.

- generators/chipyard/src/main/scala/config/fragments/SubsystemFragments.scala
This improves PD of cache banks
**Impact**:
> Add cfg fragment to insert LLC interior/exterior buffers

- fpga/src/main/scala/arty100t/Configs.scala
- fpga/src/main/scala/arty100t/HarnessBinders.scala
- generators/chipyard/src/main/scala/config/fragments/ClockingFragments.scala
> Add Bringup on Arty100T config, using PMOD-gpio for ser-tl

- common.mk
If a design has no blackboxes it might not generate a black-box filelist (`MFC...BB_FILELIST`). This breaks the flow (since a `sed` needs it downstream). Instead always generate it.
**Impact**:
> Always generate MFC Blackbox filelist

- tests/blkdev.c
The block device controller assumes that the incoming requests from the block device driver is aligned to 64B.
This assumption is not met in the baremetal test, resulting in a tilelink assertion to fire.
This PR fixes the baremetal test.
**Impact**:
> fix blkdev test

- .github/scripts/defaults.sh
- fpga/Makefile
- fpga/src/main/scala/arty/HarnessBinders.scala
- fpga/src/main/scala/arty/TestHarness.scala
Rename the arty config to arty35t config to avoid confusion.
Now, instead of 
```bash
make SUB_PROJECT=arty bitstream
```
the command for making 35T configuration becomes
```bash
make SUB_PROJECT=arty35t bitstream
```
This change is made to keep Arty 35t configuration with the same naming convention as the Arty 100t configuration.
**Impact**:
> REFACTOR: rename arty35t explicitly

- generators/chipyard/src/main/scala/harness/MultiHarnessBinders.scala
- generators/chipyard/src/main/scala/harness/package.scala
In general, users should be able to generate arb. RTL in the harness and connect up any clock they want to it (for example to connect up a queue between IOs, debugging loggers, etc). This is supported with current `HarnessBinders` but not with `MultiHarnessBinders` specifically because the `Multi*` version doesn't have access to `th: HasHarnessInstantiators`. This adds this back to the `MultiHarnessBinder` when it was dropped on the PortAPI changes.
**Impact**:
> Add HasHarnessInstantiators into MultiHarnessBinder

- scripts/replace-content.py
This fixes problems in environments which set python2 as python.
**Impact**:
> replace-content.py should use python3 explicitly

- generators/chipyard/src/main/scala/config/NoCConfigs.scala
- generators/chipyard/src/main/scala/config/TutorialConfigs.scala
This adds a SbusMeshConfig, which implements a more aggressive low-latency configuration of the Constellation NoC, that is more suitable for PD and performance exploration
**Impact**:
> Bump constellation with improved TL-noc

- .gitmodules
- docs/Software/Spike.rst
- generators/chipyard/src/main/resources/csrc/spiketile.cc
- scripts/build-toolchain-extra.sh
> Add spike devices

- generators/chipyard/src/main/scala/iobinders/IOBinders.scala
I recently noticed a performance degradation when emitting FIRRTL for a private SoC project, and tracked the issue down to this bit of IOBinders code. If you add a `println` statement to the `IOBinder` class, like this:
```diff
diff --git a/generators/chipyard/src/main/scala/iobinders/IOBinders.scala b/generators/chipyard/src/main/scala/iobinders/IOBinders.scala
index 45f72641..f67e7bf3 100644
--- a/generators/chipyard/src/main/scala/iobinders/IOBinders.scala
+++ b/generators/chipyard/src/main/scala/iobinders/IOBinders.scala
@@ -116,7 +116,10 @@ object GetSystemParameters {
}
class IOBinder[T](composer: Seq[IOBinderFunction] => Seq[IOBinderFunction])(implicit tag: ClassTag[T]) extends Config((site, here, up) => {
-  case IOBinders => up(IOBinders, site) + (tag.runtimeClass.toString -> …
```
> Reduce CDE lookups for IOBinders

- docs/Chipyard-Basics/Initial-Repo-Setup.rst
When using conda-lock=1.4 constraint, it will install version greater than v1.4.**0**. With that version, `build-setup.sh` will halt with the following error:
**Impact**:
> FIX: fix conda-lock version, >1.4.0 does not work!

- common.mk
This provides a more useful error for uninitialized submodules.
**Impact**:
> Add generators/ submodule status check to all Make targets

- generators/chipyard/src/main/scala/SpikeTile.scala
- generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala
- generators/chipyard/src/main/scala/clocking/TileClockGater.scala
- generators/chipyard/src/main/scala/clocking/TileResetSetter.scala
- generators/chipyard/src/main/scala/iobinders/IOBinders.scala
These are currently compiler warnings, and becomes compiler errors when updating to Chisel 5.
- `IO` was moved from `chisel3.experimental` to `chisel3`
- `DataMirror` was moved from `chisel3.experimental` to `chisel3.reflect`
**Impact**:
> Update deprecated APIs to prepare for Chisel 5

- scripts/build-setup.sh
Easier to remember flags than numbers.
**Impact**:
> Add clearer --skip flags to build-setup

- scripts/uniquify-module-names.py
On macOS, this can be set to `gsed` to allow use of the `-i` flag.
**Impact**:
> Allow sed override in uniquify-module-names.py

- variables.mk
- vlsi/power.mk
- vlsi/sim.mk
> Rename timeout_cycles to TIMEOUT_CYCLES to match convention

- docs/Generators/TestChipIP.rst
- generators/chipyard/src/main/scala/DigitalTop.scala
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/config/ChipletConfigs.scala
- generators/chipyard/src/main/scala/harness/HarnessBinders.scala
- generators/chipyard/src/main/scala/iobinders/IOBinders.scala
- generators/chipyard/src/main/scala/iobinders/Ports.scala
Adds a chip ID port that is used to assign a chip ID to each chip within a config. The port drives a MMIO register (see [testchipip/#212](https://github.com/ucb-bar/testchipip/pull/212)). Currently, the port value is hardcoded in WithChipIdPinFromHarness, but the harness binder will be modified in the future to use the chipId argument (see #1716).
The purpose of this PR is to enable cache coherency across multi-chip configs in Chipyard.
**Impact**:
> Add Chip ID Pin and Port

- .readthedocs.yml
- conda-reqs/chipyard.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
- conda-reqs/docs.yaml
- scripts/generate-conda-lockfiles.sh
The RTD changed to not allow lock-files in the `.readthedocs.yaml` configuration. So now, lets instead use the environment file directly.
**Impact**:
> Use non-lock-file conda requirements in RTD

- .github/actions/run-tests/action.yml
- .github/scripts/remote-do-rtl-build.sh
- .github/scripts/remote-run-firesim-scala-tests.sh
- .github/workflows/chipyard-full-flow.yml
- .github/workflows/chipyard-run-tests.yml
- scripts/build-setup.sh
- scripts/init-submodules-no-riscv-tools-nolog.sh
The default installation option should not ask "y/n".
I think most people would want to run `build-setup.sh` and walk away 🥲 
**Impact**:
> Remove skip-validate option

- common.mk
- scripts/split-mems-conf.py
I believe these changes should fix the constant-rebuild problem.
The problem was that after the first run, some of the steps (macro-compile/split-mems) would not update the timestamp of the output files since the scripts would see that those files always exist. This causes those files to be perpetually out-of-date, forcing constant builds.
**Impact**:
> Fix unnecessary runs/rebuilds of RTL simulators

- scripts/build-setup.sh
> Remove useless conda env sourcing

- .gitmodules
- scripts/init-submodules-no-riscv-tools-nolog.sh
- Prevents recursive clones of nvdla/cva6
- Fixes recusive clones of rocket-chip not respecting submodule.update=none
**Impact**:
> Fix submodule recusive cloning

- docs/Customization/MMIO-Peripherals.rst
- generators/chipyard/src/main/scala/example/GCD.scala
With recent rocket-chip bumps. the example GCD MMIO peripheral had to update. Given that many people base their own MMIO peripheral implementations off the example GCD, I thought it best to update the example GCD to match a more "standard" style of peripheral device construction.
This change
- Reduces the number of traits in the example
- Switches to a more straightforward LazyModule + node structure, instead of the opaque (and to-be-deprecated) TLRegisterRouter API
- Sacrifices concision for clarity, the examples for AXI and TL duplicate some code, but this makes each example clearer
- Demonstrates how to declare a peripheral as a ClockSinkDomain, which enables it to be placed under BaseSubsystem without being wrapped in another layer of module hierarchy.
**Type …
> Improve GCD example

- variables.mk
Makes it easy to run a list of binaries in a directory
**Impact**:
> Support BINARIES_DIR make flag

- docs/Customization/Incorporating-Verilog-Blocks.rst
- docs/Customization/MMIO-Peripherals.rst
- docs/TileLink-Diplomacy-Reference/NodeTypes.rst
- docs/TileLink-Diplomacy-Reference/Register-Node.rst
- docs/TileLink-Diplomacy-Reference/index.rst
> Update MMIO peripheral docs

- vlsi/Makefile
previously the target would append, not truncate
the file, which could lead to duplicate yaml entries in that file when the target was re-run.
**Impact**:
> vlsi/Makefile: truncate file SRAM_GENERATOR_CONF

- .github/workflows/update-circt.yml
Change the version of the update-circt action from v1.0.0 to v1.  This pulls in a change from v1.0.1 which fixes a bug where the staging branch was not updated.  (I have no idea if this is being used.)  However, this generally future-proofs the action by having it pull from v1 which is manually updated to match the latest v1 release (pulling in minor and patch changes).
> Switch update-circt action to v1

- common.mk
- variables.mk
> Allow passing BINARY_ARGS to target binaries (pk)

- generators/chipyard/src/main/scala/DigitalTop.scala
- generators/chipyard/src/main/scala/config/PeripheralDeviceConfigs.scala
- generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala
Some people use this block, so it should be in the regressions.
**Impact**:
> Add example rocket-chip-blocks timer integration

- generators/chipyard/src/main/scala/iobinders/IOBinders.scala
Resolves ucb-bar/chipyard#1731.
**Impact**:
> Ensure all GPIO signals are tied off

- fpga/src/main/scala/vcu118/Configs.scala
- fpga/src/main/scala/vcu118/HarnessBinders.scala
- fpga/src/main/scala/vcu118/TestHarness.scala
The JTAG IO pins are mapped to FMC pins. 
changelog:added
#1785 
**Impact**:
> Enabling JTAG Debuging in VCU118 FPGA changelog:added

- scripts/uniquify-module-names.py
In Python 3.12, these show up as SyntaxWarning messages.
**Impact**:
> Fix invalid escape sequences

- docs/Chipyard-Basics/Initial-Repo-Setup.rst
- docs/Simulation/FPGA-Accelerated-Simulation.rst
Some docs about FireSim is a bit out-dated:
1. After `source sourceme-manager.sh`, we need `firesim managerinit --platform f1` to do some extra prep work before continuing.
2. `sims/firesim/deploy/deploy/config_build_recipes.ini` doesn't exist, it was refactored into `sims/firesim/deploy/config_build_recipes.yaml`
3. Fix some broken links to FireSim docs
Also, I added a reference to FireSim docs on [how to build custom hardware design with FireSim](https://docs.fires.im/en/stable/Getting-Started-Guides/AWS-EC2-F1-Getting-Started/Initial-Setup/Setting-up-your-Manager-Instance.html), should be beneficial to include that.
**Impact**:
> docs: Update FireSim docs

- conda-reqs/chipyard-base.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64-lean.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64-lean.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
**Impact**:
Verilator v5.020 has a bug when building a debug simulator (https://github.com/verilator/verilator/issues/4860). Bumping the Verilator version resolves this issue.
> Bump to Verilator v5.022

- .gitmodules
Rearranges the submodule entries in `.gitmodules` to match the order of appearance in file directory. This should allow adding / removing submodules easier and should not affect anything.
**Impact**:
> REFACTOR: rearrange gitsubmodule list to match directory order

- .github/scripts/check-commit.sh
- .gitmodules
- build.sbt
- fpga/src/main/scala/arty/HarnessBinders.scala
- fpga/src/main/scala/arty100t/Configs.scala
- fpga/src/main/scala/arty100t/HarnessBinders.scala
- fpga/src/main/scala/nexysvideo/Configs.scala
- fpga/src/main/scala/nexysvideo/HarnessBinders.scala
- fpga/src/main/scala/vc707/HarnessBinders.scala
- fpga/src/main/scala/vcu118/HarnessBinders.scala
- generators/chipyard/src/main/scala/DigitalTop.scala
- generators/chipyard/src/main/scala/Subsystem.scala
- generators/chipyard/src/main/scala/System.scala
- generators/chipyard/src/main/scala/example/CustomChipTop.scala
- generators/chipyard/src/main/scala/example/FlatChipTop.scala
- generators/chipyard/src/main/scala/example/GCD.scala
- generators/chipyard/src/main/scala/example/InitZero.scala
- generators/chipyard/src/main/scala/example/dsptools/GenericFIR.scala
- generators/chipyard/src/main/scala/example/dsptools/StreamingPassthrough.scala
- generators/chipyard/src/main/scala/iobinders/IOBinders.scala
- generators/chipyard/src/main/scala/iobinders/Ports.scala
- generators/tracegen/src/main/scala/System.scala
> Bump rocket-chip to standalone diplomacy

- conda-reqs/chipyard-base.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64-lean.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64-lean.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
- conda-reqs/riscv-tools.yaml
- fpga/src/main/resources/vcu118/sdboot/Makefile
- scripts/build-toolchain-extra.sh
- tests/hello.c
**Impact**:
Motivation for the bump is: 1) We should try to use the latest gcc to see if there are any regressions, 2) we should take advantage of any new compiler optimizations, and 3) verilator supposedly performs much better on large designs with `-Oz` which only exists in modern gcc. For now, I just want to see what breaks in CI.
> Bump to gcc 13

- generators/chipyard/src/main/scala/config/MMIOAcceleratorConfigs.scala
- generators/chipyard/src/main/scala/example/InitZero.scala
> Fix InitZero example + add to CI

- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/config/fragments/TileFragments.scala
Default to using SV48 for 64b designs. Otherwise, adhere to the RC default (SV32).
**Impact**:
> Use SV48 when possible

- docs/Simulation/Software-RTL-Simulation.rst
The Software RTL Simulation docs mention an output executable however its name is different.
**Impact**:
> [docs] Fix sim output executable name usage in docs (NFC)

- docs/Advanced-Concepts/Top-Testharness.rst
- generators/chipyard/src/main/scala/config/NoCoreConfigs.scala
- generators/chipyard/src/main/scala/example/EmptyChipTop.scala
- generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala
- scripts/split-mems-conf.py
This shows how to replace the soc-oriented ChipTop with an empty one that can be filled with whatever the user wants. 
Useful for teaching people how the system works, or for setting up one-off experiments.
**Impact**:
> Add EmptyChipTop example

- common.mk
- docs/Customization/Firrtl-Transforms.rst
- variables.mk
Fixed types are never generated now. Custom SFC passes/flags are not known to be used. Preps the way for chisel6
**Impact**:
> Remove legacy SFC flags

- generators/chipyard/src/main/scala/System.scala
- generators/chipyard/src/main/scala/harness/MultiHarnessBinders.scala
- Fixes issue where MultiHarnessBinders couldn't attach two ports of a different type. This matters cases where a the `Port` object might be slightly different from source to sink. 
- Fixes case where `TLMonitor` might not get an implicit clock from the `DigitalTop` module causing an obscure error during elaboration. This fix isn't needed for the AXI4 ports since there is no AXI4 monitor implementation in RC yet, thus no monitors are created for them.
**Impact**:
> Update MultiHarnessBinders to connect differently typed ports + Ignore TLMonitors on DigitalTop scope

- generators/chipyard/src/main/scala/config/fragments/TileFragments.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
> add sv39 fragments

- build.sbt
- common.mk
- docs/Prototyping/General.rst
- fpga/Makefile
- variables.mk
Previously, the chipyard.jar cache was built with SBT_PROJECT (usually chipyard) as the top-level project. This causes a bug where after building the jar with SBT_PROJECT=chipyard, future fpga compilations (with SBT_PROJECT=fpga_platforms) would fail due to not rebuilding the cache.
This PR updates the build system to build a separate jar for the fpga flow that includes the fpga-specific sources.
This renames `fpga_platforms` to `chipyard_fpga` to make it clearer that that project is an extension of chipyard with fpga configs.
This renames `CHIPYARD_CLASSPATH` to `GENERATOR_CLASSPATH` to make it clearer that the this classpath must contain a `Generator` main to run, but it does not have to be the chipyard project in build.sbt
**Impact**: …
> Fix classpath_cache bug

- vlsi/example-asap7.yml
- vlsi/example-design.yml
- vlsi/example-designs/sky130-commercial.yml
- vlsi/example-designs/sky130-openroad-rockettile.yml
- vlsi/example-designs/sky130-openroad.yml
- vlsi/example-designs/sky130-rocket.yml
- vlsi/example-sky130.yml
As usual, the clock name and SRAM macro paths have changed in chipyard designs. After these fixes commercial flow works, but OpenROAD is stuck on global placement so another fix is required for that.
**Impact**:
> Fix clock name and macro paths for Sky130 VLSI flow

- generators/chipyard/src/main/scala/clocking/ClockBinders.scala
- generators/chipyard/src/main/scala/config/ClockingConfigs.scala
This ClockBinder broadcasts a single clock IO to all clock domains for ultra-simple systems.
Don't merge this until the harness/clock merging is done
**Impact**:
> Add singleclock broadcast clockbinder

- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/iobinders/IOBinders.scala
- generators/chipyard/src/main/scala/iobinders/Ports.scala
> Add GCD IOBinders examples

- .github/scripts/check-commit.sh
- .github/scripts/defaults.sh
- .github/scripts/run-tests.sh
- .github/workflows/chipyard-run-tests.yml
- .gitmodules
- build.sbt
- generators/chipyard/src/main/scala/DigitalTop.scala
- generators/chipyard/src/main/scala/config/RoCCAcceleratorConfigs.scala
- generators/chipyard/src/main/scala/config/fragments/RoCCFragments.scala
ReRocC (Remote RoCC) is a ISA extension, communication protocol, and RTL implementation of a system which enables physical disaggregation of RoCC accelerators and software accelerator Muxing, all while preserving most existing interfaces for RoCC accelerators.
**Impact**:
> Integrate ReRoCC

- common.mk
We don't depend on firesim's build.sbt anymore
**Impact**:
> Remove firesim build.sbt from our SBT dependencies

- common.mk
- variables.mk
> Generate a log file of the CIRCT output

- scripts/insert-includes.py
Encapsulate some functionalities of the insert_includes.py into sub functions to be more readable. 
Process includes in a single pass through the temp file with DFS
Format according to pep8 style
**Impact**:
> Improve insert includes

- .github/scripts/check-commit.sh
- .github/scripts/defaults.sh
- .github/scripts/run-tests.sh
- .github/workflows/chipyard-run-tests.yml
- .gitmodules
- build.sbt
- docs/Generators/CompressAcc.rst
- docs/Generators/index.rst
- generators/chipyard/src/main/scala/config/RoCCAcceleratorConfigs.scala
> Add compress-acc

- fpga/src/main/scala/vc707/Configs.scala
- fpga/src/main/scala/vcu118/Configs.scala
- generators/chipyard/src/main/scala/SpikeTile.scala
- generators/chipyard/src/main/scala/config/MMIOAcceleratorConfigs.scala
- generators/chipyard/src/main/scala/config/MemorySystemConfigs.scala
- generators/chipyard/src/main/scala/config/NoCConfigs.scala
- generators/chipyard/src/main/scala/config/PeripheralDeviceConfigs.scala
- generators/chipyard/src/main/scala/config/RoCCAcceleratorConfigs.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala
- generators/chipyard/src/main/scala/config/fragments/SubsystemFragments.scala
- generators/chipyard/src/main/scala/example/TutorialTile.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
> Update rocket-chip with modern diplomacy/prci packaging

- build.sbt
- generators/chipyard/src/main/scala/clocking/ClockBinders.scala
- generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala
- generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/config/ChipConfigs.scala
- generators/chipyard/src/main/scala/config/NoCoreConfigs.scala
> Bump rc/components to improve module naming

- generators/chipyard/src/main/resources/csrc/spiketile.cc
- generators/chipyard/src/main/scala/SpikeTile.scala
- generators/chipyard/src/main/scala/iobinders/IOBinders.scala
- scripts/generate-ckpt.sh
> Bump Spike

- generators/firechip/src/main/scala/BridgeBinders.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
Adds a FireSim DMI Bridge for an alternative bringup interface other than TSI.
- Adds a new DMI target config for FireSim for quick testing
- Adds bridge binder for DMI
- Enables DebugModule for all FireSim designs (now that clock gating can be disabled). This matches CY's behavior of always having it.
**Impact**:
> Add DMI Bridge to FireSim

- fpga/src/main/scala/arty/Configs.scala
- fpga/src/main/scala/vc707/Configs.scala
- fpga/src/main/scala/vcu118/Configs.scala
- generators/chipyard/src/main/scala/SpikeTile.scala
- generators/chipyard/src/main/scala/TestSuites.scala
- generators/chipyard/src/main/scala/config/ChipConfigs.scala
- generators/chipyard/src/main/scala/config/ChipletConfigs.scala
- generators/chipyard/src/main/scala/config/ClockingConfigs.scala
- generators/chipyard/src/main/scala/config/HeteroConfigs.scala
- generators/chipyard/src/main/scala/config/IbexConfigs.scala
- generators/chipyard/src/main/scala/config/MMIOAcceleratorConfigs.scala
- generators/chipyard/src/main/scala/config/MemorySystemConfigs.scala
- generators/chipyard/src/main/scala/config/NoCConfigs.scala
- generators/chipyard/src/main/scala/config/PeripheralDeviceConfigs.scala
- generators/chipyard/src/main/scala/config/RoCCAcceleratorConfigs.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- generators/chipyard/src/main/scala/config/SodorConfigs.scala
- generators/chipyard/src/main/scala/config/TutorialConfigs.scala
- generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala
- generators/chipyard/src/main/scala/config/fragments/SubsystemFragments.scala
- generators/chipyard/src/main/scala/config/fragments/TileFragments.scala
- generators/chipyard/src/main/scala/example/TutorialTile.scala
- generators/firechip/src/main/scala/TargetConfigs.scala
- generators/tracegen/src/main/scala/Configs.scala
- tools/stage-chisel3/src/main/scala/phases/AddDefaultTests.scala
- tools/stage/src/main/scala/phases/AddDefaultTests.scala
> Bump rocket-chip/submods for reorganized rocket configs

- common.mk
- variables.mk
> Add makefile flag to disable binary disassembly during sims

- generators/chipyard/src/main/scala/config/BoomConfigs.scala
This PR adds the configuration combining the MegaBoom and SimBlockDevice for running Linux inside Verilator simulation.
**Impact**:
> Add configuration for MegaBoom that uses SimBlockDevice

- build.sbt
- tools/stage/src/main/scala/ChipyardStage.scala
> Bump to chisel 6.5.0

- .github/dependabot.yml
Opening this to spawn discussion on how/should we use this to update submodules. I think this is nice, but we should 1. configure how often it checks for things and 2. what it should update v.s. what we should do ourselves. In any case, the PRs that it opens still have to be manually approved (see FireSims PRs from dependabot: https://github.com/firesim/firesim/pulls)
**Impact**:
> Add dependabot to auto-update submodules

- .github/workflows/chipyard-full-flow.yml
- Pin SRAM macros repo for SKY130 to a specific commit
- Update VLSI CI conda env creation to use specific channels directly instead of modifying the base environment before/after creating new environments. This avoids CI modifying the base conda environment / making it more robust.
**Impact**:
> Fix VLSI CI - Fix conda environment creation

- .github/workflows/chipyard-full-flow.yml
Fixes issue where CI would run out of disk space on `/tmp`. 
**Impact**:
> Run CI out of larger scratch directory

- fpga/src/main/scala/nexysvideo/Configs.scala
- fpga/src/main/scala/nexysvideo/HarnessBinders.scala
> Nexys video fpga bringup config

- .gitmodules
Adds the FireSim paper workloads. Additionally, makes modifications to them s.t. they build w/ FireMarshal's `mountImg` function (so that they don't need sudo to build).
**Impact**:
> Add FireSim paper tests (migrating them from FireSim)

- .github/workflows/chipyard-full-flow.yml
- .github/workflows/chipyard-run-tests.yml
See title. Allows users to add a label `ci:disable` to disable CI.
**Impact**:
> Add CI disable flag

- README.md
- docs/Generators/Saturn.rst
* Rocket-chip now supports vector-extensions
* Fixes minor bug in shuttle load-stores
* Saturn now supports zvbb
**Impact**:
> Bump rocket-chip/saturn/shuttle

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/chipyard-full-flow.yml
- .github/workflows/chipyard-run-tests.yml
- .github/workflows/firesim-cluster-tests.yml
Misc. QoL updates to clarify things.
**Impact**:
> Add CI help text to PR template | Reduce more CI runs

- fpga/src/main/scala/arty/Configs.scala
- fpga/src/main/scala/arty100t/Configs.scala
- fpga/src/main/scala/nexysvideo/Configs.scala
- fpga/src/main/scala/vc707/Configs.scala
- fpga/src/main/scala/vcu118/Configs.scala
- generators/chipyard/src/main/scala/config/ChipConfigs.scala
- generators/chipyard/src/main/scala/config/PeripheralDeviceConfigs.scala
- generators/chipyard/src/main/scala/config/SpikeConfigs.scala
- generators/chipyard/src/main/scala/config/TracegenConfigs.scala
- generators/chipyard/src/main/scala/config/fragments/ClockingFragments.scala
- generators/chipyard/src/main/scala/harness/HarnessBinders.scala
> Add WithUniformBusFrequencies | Fix UARTTSI HarnessBinder

- scripts/build-tests.sh
- tests/CMakeLists.txt
- tests/README.md
This PR addresses #2049.
README documentation is added in tests folder to demonstrate usage of the CMake command. A general usage example can also be found in the header of CMakeLists.txt itself.
The `<test_name>-dump` commands and `dump` command are added to the CMake flow to enable generation of disassembly files of the tests.
The script is removed since it creates unnecessary overhead in the build flow. User should use the cmake commands directly and build the desired target.
**Impact**:
**CI Help**:
See `ci:*` for full list of …
> ADD: add dump flow and documentation on tests building

- .github/scripts/check-commit.sh
- .github/scripts/defaults.sh
- .github/scripts/run-tests.sh
- .github/workflows/chipyard-run-tests.yml
- .gitmodules
- build.sbt
- docs/Chipyard-Basics/Chipyard-Components.rst
- docs/Generators/Shuttle.rst
- docs/Generators/VexiiRiscv.rst
- docs/Generators/index.rst
- generators/chipyard/src/main/scala/config/VexiiRiscvConfigs.scala
- generators/chipyard/src/main/scala/config/fragments/TileFragments.scala
- scripts/init-submodules-no-riscv-tools-nolog.sh
VexiiRiscv is a dual-issue in-order Linux-capable SpinalHDL RISCV implementation.
**Impact**:
**CI Help**:
> Add vexiiriscv CPU support

- CHANGELOG.md
> Add CHANGELOG for 1.13.0 release

- sims/firesim-staging/sample_config_hwdb.yaml
> chore: bump boom for ordering fix

- conda-reqs/chipyard-base.yaml
- conda-reqs/chipyard-extended.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64-lean.conda-lock.yml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
Similar to https://github.com/firesim/firesim/pull/1805. Also, adds `ninja` in case users need to build CIRCT from source.
**Impact**:
**CI Help**:
> Downgrade bcrypt<4.0.0 for FireSim on AWS EC2 Centos7 + Install ninja by default for building CIRCT

- .github/scripts/run-tests.sh
- tests/CMakeLists.txt
Tests should be compiled into whatever the build directory is
**Impact**:
**CI Help**:
> Don't specify a nondefault CMAKE_RUNTIME_OUTPUT_DIRECTORY

- docs/Chipyard-Basics/Initial-Repo-Setup.rst
libmamba has been the default solver for a little over a year, so we don't need to manually install it:
https://conda.org/blog/2023-11-06-conda-23-10-0-release/
**Impact**:
**CI Help**:
> docs: libmamba is now the default solver in conda

- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/config/PeripheralDeviceConfigs.scala
- generators/chipyard/src/main/scala/harness/HarnessBinders.scala
- generators/chipyard/src/main/scala/iobinders/IOBinders.scala
> Add I2C peripheral example

- generators/firechip/chip/src/main/scala/FireSim.scala
See title. Disabled (i.e. commented out) instead of doing an `if(p(FireSimFAME5))` type statement wrapping the problematic annotation since `p(FireSimFAME5)` is always enabled from the target POV (by default added in `BridgeBinders.scala` with `WithFireSimFAME5`). This optimization breaks model multi-threading (for CPU tiles). With this commented out, model multi-threading should work again.
**Impact**:
**CI Help**:
- …
> Disable FPU model optimizations (temporarily)

- fpga/src/main/scala/arty100t/Configs.scala
- fpga/src/main/scala/arty100t/HarnessBinders.scala
- fpga/src/main/scala/datastorm/Configs.scala
- fpga/src/main/scala/datastorm/HarnessBinders.scala
- fpga/src/main/scala/nexysvideo/HarnessBinders.scala
- generators/chipyard/src/main/scala/config/AbstractConfig.scala
- generators/chipyard/src/main/scala/config/ChipConfigs.scala
- generators/chipyard/src/main/scala/config/ChipletConfigs.scala
- generators/chipyard/src/main/scala/example/FlatTestHarness.scala
- generators/chipyard/src/main/scala/harness/HarnessBinders.scala
- generators/chipyard/src/main/scala/harness/MultiHarnessBinders.scala
- generators/firechip/chip/src/main/scala/BridgeBinders.scala
- generators/firechip/chip/src/main/scala/TargetConfigs.scala
This improves the naming of the Serial-TL parameterization objects to make it clearer what is generated.
The Decoupled{Internal/External}SyncPhy implementation was determined to be deadlocking, although the condition under which deadlock could occur is effectively impossible on real silicon ... deadlock is only possible if both sides fully saturate the channel and run at the same frequency.
This PR adds a loud warning in the generator when building with that form of flow control.... it should still be safe for test chips, as the chip-FPGA link is always throttled by the FPGA, or by the UART-TSI onto the FPGA.
**Impact**:
**CI Help**:
Generally, a label …
> Improve naming of Serial-TL PhyParams

- .github/scripts/defaults.sh
- .github/scripts/run-tests.sh
- .github/workflows/chipyard-run-tests.yml
- generators/chipyard/src/main/scala/config/ShuttleConfigs.scala
> 3-wide shuttle

- fpga/src/main/scala/arty/HarnessBinders.scala
- fpga/src/main/scala/arty100t/HarnessBinders.scala
- fpga/src/main/scala/vcu118/HarnessBinders.scala
- generators/chipyard/src/main/scala/example/FlatChipTop.scala
- generators/chipyard/src/main/scala/harness/HarnessBinders.scala
- generators/chipyard/src/main/scala/iobinders/IOBinders.scala
> Support externally-driven separate JTAG reset pin

- generators/chipyard/src/main/scala/example/TutorialTile.scala
See https://github.com/chipsalliance/rocket-chip/pull/3723
https://github.com/ucb-bar/chipyard/issues/2205
**Impact**:
**CI Help**:
> Remove deprecated rocket-chip annotation API

- build.sbt
Bump submodules to remove deprecated `ChiselAnnotation` API, which is going away in Chisel 7. Submodule PRs:
- https://github.com/chipsalliance/rocket-chip/pull/3724
- https://github.com/chipsalliance/diplomacy/pull/19
- https://github.com/ucb-bar/constellation/pull/82
Chisel release notes:
- https://github.com/chipsalliance/chisel/releases/tag/v6.6.0
- https://github.com/chipsalliance/chisel/releases/tag/v6.7.0
**Impact**:
**CI Help**:
- …
> Update to Chisel 6.7, use new annotation API

- common.mk
- fpga/src/main/scala/vc707/Configs.scala
- fpga/src/main/scala/vcu118/Configs.scala
- generators/chipyard/src/main/scala/DigitalTop.scala
- generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala
- generators/chipyard/src/main/scala/iobinders/IOBinders.scala
- generators/firechip/chip/src/main/scala/TargetConfigs.scala
- variables.mk
This removes the BootROM copying hack
**Impact**:
**CI Help**:
> Update to newer rocket-chip

- conda-reqs/chipyard-extended.yaml
- conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
- scripts/build-setup.sh
**Edit 1**
At some point the `build-setup.sh` line:
```
conda-lock install --conda $CONDA_EXE $CONDA_ENV_ARG $LOCKFILE &&
```
Got changed to:
```
conda-lock install --conda $(which conda) $CONDA_ENV_ARG $LOCKFILE &&
```
Which does not work in all cases (such as BWRC and EDA machines), due to this behavior of `which conda`:
- https://superuser.com/questions/1602014/which-conda-doesnt-output-a-path
As seen in the issues here:
- https://github.com/ucb-bar/chipyard/issues/2016
- https://github.com/ucb-bar/chipyard/issues/2002
- https://github.com/ucb-bar/chipyard/issues/2073
Specifically it causes this build error:
```
Using lockfile for conda: [redacted]/conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
Storing main conda environment in …
```
> small build setup edits to prevent common failures

- generators/chipyard/src/main/scala/config/MMIOAcceleratorConfigs.scala
- generators/chipyard/src/main/scala/config/RocketConfigs.scala
- generators/chipyard/src/main/scala/config/TutorialConfigs.scala
> Remove no-dont-touch hack - this bug has been fixed in newer CIRCT

- build.sbt
- generators/chipyard/src/main/scala/DigitalTop.scala
- generators/chipyard/src/main/scala/example/InitZero.scala
- generators/chipyard/src/main/scala/example/dsptools/GenericFIR.scala
- generators/chipyard/src/main/scala/example/dsptools/StreamingPassthrough.scala
This adds a API to rocket-chip that allow devices to inject themselves into the BaseSubsystem without requiring a `CanHavePeripheryX` trait. This only works for devices that don't generate top-level IO.
This makes it possible to make these devices optional as  the chipyard-lite PR #2212 
**Impact**:
**CI Help**:
> Remove cake-pattern requirement for no-IO devices

- docs/Advanced-Concepts/Chip-Communication.rst
- docs/conf.py
Import detailed JTAG + GDB debugging instructions from the RocketChip README into Chipyard's documentation. This improves the Chip-Communication section with guidance for debugging RISC-V programs using the Remote Bit-Bang interface, OpenOCD, and GDB.
Documentation was sourced from this archive of the RocketChip README:
https://github.com/chipsalliance/rocket-chip/blob/0b7fef44f82b35bf289949b3f8fdc139641f8e10/README.md
Additionally, this PR changes the docs/conf.py so that you may test the Sphinx build locally by replacing hardcoded GitHub repo URL with a dynamic solution that uses the actual git remote URL. This fixes documentation builds in forks by generating correct file links to the user's repository instead of pointing to the original repo.
The implementation:
- Detects GitHub …
> Incorporate RocketChip JTAG + GDB debugging instructions, improve docs/conf.py for local development

- common.mk
- sims/vcs/Makefile
- sims/verilator/Makefile
- sims/xcelium/Makefile
> Relax checks for vcs/verilator/xcelium in PATH

- .github/workflows/chipyard-full-flow.yml
- common.mk
- docs/Customization/Keys-Traits-Configs.rst
- docs/Simulation/Software-RTL-Simulation.rst
- generators/chipyard/src/main/scala/ConfigFinder.scala
> Add full-config-finder: finds eligible CONFIG targets

- common.mk
- variables.mk
> Allow overriding firtool in PATH with FIRTOOL_BIN flag

- tools/tapeout/src/main/scala/macrolib/SRAM.scala
- tools/tapeout/src/main/scala/macros/MacroCompiler.scala
This is to support the TSTECH16C SRAM generators. The depth/widths supported is not a linear sequence; also, some combinations of valid depth and valid width is not valid (thus the triple option). This change should not have any impact on existing SRAM generators, since it looks for the JSON keys `depth list`, `width list`, or `triples`.
`triples` will take precedence, followed by the explicit lists, and then finally the fallback is the current scheme of specifying 3 numbers (start, end, step). If nothing is found, the compilation fails (like it currently does).
**Impact**:
**CI Help**:
Generally, a label added only affect subsequent changes to the PR …
> Support sram depth/width lists, as well as explicit list of legal combos
