ucb-bar/chipyard

Makefrag
README.md

@zhemao Hopefully this is what you had in mind.

Publish firrtl locally first, to make Chisel happy

---

Makefrag
README.md

This addresses #4 and #6.
It ended up being much closer to #4 than I thought back then. Sorry @ben-k

Build firrtl first so we dont get that weird error

---

src/main/scala/example/PWM.scala

I accidentally stumbled into a working AXI4 configuration by multiplying pbus.beatBytes by 8, but it was fragile. This is the "right way" to add an AXI4 peripheral.

Fix AXI4 example.

---

common.mk

Bump barstools and re-add infer-rw for better SRAM mapping

---

Makefrag

Goes with https://github.com/ucb-bar/barstools/pull/54 and updates the build system to emit the desired firrtl/annotations files.

Build additional annos and fir

---

Makefrag

Hopefully I got all the references. @jwright6323 was the last one to touch this so I'd appreciate a review.
Tested building simulators in both verisim and vsim

Use SBT for barstools instead of jars

---

common.mk
project/plugins.sbt
sims/verisim/Makefile
sims/vsim/Makefile
src/main/scala/example/Simulator.scala
variables.mk

Now allows for `make` to run. Also aligns with the commits that John/Colin did in the main repo.

align rebar with tip of project-template master | fixes build issues

---

scripts/regression.sh

Super basic tests that should finish and pass.

add basic regression script

---

.gitmodules
build.sbt
common.mk
sims/verisim/Makefile
sims/vsim/Makefile
src/main/scala/example/Configs.scala
variables.mk

~Building Hwacha configs located in the Hwacha package does not work due to file naming issues.~
~Building Hwacha configs located in the Hwacha package seems to cause multiple elaborations.~

[rebar] adding Hwacha

---

Makefrag
src/main/scala/example/Configs.scala
src/main/scala/example/TestHarness.scala
verisim/Makefile
vsim/Makefile

Just a place holder for those interested. Points to a branch of rocket-chip now, so will need to clean that up before merging.
Also going to test this in my downstream templates to make sure "real" memories still work.

bump rocket-chip to enable large memory spaces

---

common.mk
variables.mk

[WIP] Bump to May rocketchip | Support for large memory spaces

---

generators/beagle/src/main/scala/ConfigMixins.scala

I've built this in verisim, and it generates the RTL successfully.
@abejgonzalez

Updated systolic parameters

---

common.mk

Remove CHISEL_ARGS

---

sims/verisim/verilator.mk

Bump Verilator to correspond with the Chisel CI bump.
Link: https://github.com/ucb-bar/chisel-ci-infra/pull/4

bump verilator version

---

docs/Advanced-Usage/Heterogeneous-SoCs.rst
docs/Advanced-Usage/index.rst
docs/index.rst
generators/example/src/main/scala/Configs.scala

Explains how to use MultiRoCC and create multi-core systems with both BOOM and RoCC. Also creates a 'Advanced-Usage' section to hold this.

Doc Update on Heter. Systems

---

common.mk
sims/verisim/Makefile
sims/vsim/Makefile
variables.mk

If you are generating a vpd you aren't going to go much slower with verbose on, and its a useful debugging tool.

Add verbose to debug runs

---

.circleci/check-commit.sh
.gitmodules
scripts/init-submodules-no-riscv-tools.sh
vlsi/.gitignore
vlsi/Makefile
vlsi/README.md
vlsi/example-vlsi

This is not usable, but this is all the non-tech specific stuff needed to run the VLSI flow. Tech-specific repos should branch off from here.

Add initial VLSI flow scripts

---

scripts/firesim-setup.sh

See the corresponding FireSim PR.
https://github.com/firesim/firesim/pull/319

Fix git submodule initialization in FireSim setup

---

variables.mk

I use this all the time downstream.

Add jvm heap size parameter

---

common.mk
variables.mk

Comment sim_* make variables

---

docs/Advanced-Usage/DTM-Debugging.rst
docs/Advanced-Usage/Resources.rst
docs/Chipyard-Basics/Configs-Parameters-Mixins.rst
docs/Customization/Boot-Process.rst
docs/Customization/Heterogeneous-SoCs.rst
docs/Customization/Memory-Hierarchy.rst
docs/Generators/BOOM.rst
generators/example/src/main/scala/HeteroConfigs.scala
generators/example/src/main/scala/RocketConfigs.scala

Misc. documentation cleanup and clarifications. I tried to match #235.

small doc clarifications + cleanup

---

CHANGELOG.md
CONTRIBUTING.md
LICENSE
README.md

Update README before 1.0 release

Pre-Release Adjustments

---

docs/Chipyard-Basics/Development-Ecosystem.rst
docs/Tools/Chisel.rst
docs/Tools/FIRRTL.rst

I prematurely merged Schuyler's changes.

Merge Master into Dev.

---

.circleci/check-commit.sh

Get the right name for the submodules in the `vlsi` folder

(master) Fix commit on master CI check

---

.circleci/check-commit.sh

Get `master` CI fix

---

.circleci/config.yml
.circleci/defaults.sh
generators/firechip/src/main/scala/TargetConfigs.scala

Temporarily Remove Support for FASED Clock Divisions

---

docs/VLSI/Tutorial.rst
vlsi/Makefile

Also fix sram-cache error. Fixes #299

[docs][ci skip] Remove extra backticks in docs

---

generators/example/src/main/scala/BoomConfigs.scala

Added a Hwacha config to the BOOM configurations. This is needed for BOOM CI.

add large boom hwacha config

---

docs/Customization/Memory-Hierarchy.rst

Previous version didn't compile as per
https://github.com/ucb-bar/chipyard/issues/365

Update scratchpad config

---

docs/Generators/SHA3.rst

This is a brief pointer to the README to help people running SHA3 tests.

[sha3] point to README for SW

---

.circleci/check-commit.sh

Backport from #362 
h/t @jerryz123

don't check prebuilt tools are on master

---

README.md

[skip ci] Fix the logo in the README

---

.gitignore

[ci-skip] Gitignore generated env-riscv-tools.sh

---

docs/Customization/RoCC-Accelerators.rst

Fix capitalization in docs

---

.circleci/config.yml

This updates the CI configuration to re-use as much configuration code as possible. This makes the config. significantly smaller and much easier to understand/modify.

Use re-usable config. components

---

docs/index.rst

[ci skip] Fix Typos

---

.gitmodules
build.sbt
common.mk
generators/chipyard/src/main/scala/BoomConfigs.scala
generators/chipyard/src/main/scala/HeteroConfigs.scala
generators/chipyard/src/main/scala/IOBinders.scala
generators/chipyard/src/main/scala/RocketConfigs.scala
generators/chipyard/src/main/scala/TracegenConfigs.scala
generators/utilities/src/main/resources/csrc/emulator.cc
generators/utilities/src/main/scala/Simulator.scala
sims/vcs/.gitignore
sims/vcs/Makefile
sims/vcs/dramsim2_ini
sims/verilator/.gitignore
sims/verilator/Makefile
sims/verilator/dramsim2_ini

https://github.com/ucb-bar/testchipip/pull/66
* Replace SimAXIMem with SimDRAM blackbox in chipyard and tracegen configurations.

Use blackboxed SimDRAM instead of SimAXIMem

---

docs/Chipyard-Basics/Initial-Repo-Setup.rst
scripts/init-submodules-no-riscv-tools-nolog.sh
scripts/init-submodules-no-riscv-tools.sh

**Related issue**: #453 
Add a git version check to the init scripts and make them work outside of the repo root.

Add a git version check to the init scripts and make them work outside of the repo root. 

---

generators/chipyard/src/main/scala/config/RocketConfigs.scala
generators/chipyard/src/main/scala/config/TracegenConfigs.scala
generators/firechip/src/main/scala/TargetConfigs.scala

**Impact**: rtl change 
* Add a TileLink network that uses a ring topology

Add ring topology system bus

---

generators/chipyard/src/main/scala/example/GCD.scala

[GCD] Fix GCD example

---

docs/Customization/RoCC-Accelerators.rst
docs/index.rst

Bump FireSim in preparation for FireSim 1.8.1 and Chipyard 1.2 releases

bump firesim

---

docs/Tools/Barstools.rst
docs/VLSI/Building-A-Chip.rst

Starting from @jwright6323 's work on a self-titled branch.

Barstools and chip docs

---

docs/Advanced-Concepts/Chip-Communication.rst
docs/Customization/DMA-Devices.rst
docs/Customization/Heterogeneous-SoCs.rst
docs/Customization/Incorporating-Verilog-Blocks.rst
docs/Customization/Keys-Traits-Configs.rst
docs/Customization/MMIO-Peripherals.rst
docs/Customization/Memory-Hierarchy.rst
docs/Generators/Gemmini.rst
docs/Generators/SHA3.rst
docs/Generators/SiFive-Generators.rst
docs/TileLink-Diplomacy-Reference/NodeTypes.rst
docs/TileLink-Diplomacy-Reference/Register-Router.rst

fix literalincludes and other path references in documentation

---

README.md

Forgot to add Gemmini to the main README but the link to the PDF is there.

Add Gemmini to README [ci skip]

---

docs/Customization/Memory-Hierarchy.rst
docs/Generators/TestChipIP.rst
generators/chipyard/src/main/scala/config/RocketConfigs.scala

Some documentation on the TLRingNetwork and ring system bus.

add documentation on ring network and system bus

---

docs/Software/Baremetal.rst
docs/Software/index.rst

Baremetal docs

---

.circleci/config.yml

Revert "Bypass approval button on dev/master"

---

project/plugins.sbt
variables.mk

This quiets down SBT a bit at startup. I also removed the now unnecessary `++<scala-version>` which may bite us laster. 

[SBT] Resolve Warnings about Jgit Resolution 

---

generators/chipyard/src/main/scala/ConfigFragments.scala

Add WithNoUART fragment

---

README.md

Update publications in README with SonicBOOM and IEEE Micro

---

scripts/init-submodules-no-riscv-tools-nolog.sh

Fixes the submodule update with Gemmini.

Fix submodule update

---

.circleci/check-commit.sh

**Related issue**: Fixes #538, Fixes #531 
**Impact**: rtl change + software change
This is bumping all submodules in Chipyard to their `master` branches in preparation for the CY 1.3 release.

Bump Submodules

---

CHANGELOG.md

Adding the changelog for the Chipyard 1.3.0 release.

Add changelog for 1.3.0 release

---

CHANGELOG.md

**Type of change**: bug fix + new feature + other enhancement
**Impact**: rtl change + software change + other
Bump to FireSim 1.10.0 and update Barstools branch for OE fix.

FireSim 1.10.0 Bump + Barstools branch update

---

README.md

Update BOOM URL in README.md

---

.circleci/check-commit.sh

Add firemarshal's dev branch to its allowed-branch list

---

generators/chipyard/src/main/scala/Subsystem.scala

DTM only supports HTIF in DMI mode

---

generators/chipyard/src/main/scala/Clocks.scala
generators/chipyard/src/main/scala/IOBinders.scala
generators/chipyard/src/main/scala/TestHarness.scala
generators/chipyard/src/main/scala/clocking/ResetSynchronizer.scala

Make the ChipTop reset pin always async

---

generators/chipyard/src/main/resources/vsrc/ClockDividerN.sv

Resolves #700.
**Related issue**: #700 

[clocking] Provide a default div for ClockDividerN sv implementation

---

sims/verilator/Makefile

Allow custom verilator optimization flags

---

docs/TileLink-Diplomacy-Reference/Register-Router.rst

Correceted minor typos

---

vlsi/Makefile

[vlsi] Add Makefile flag to use memory compiler defined in tech library

---

generators/chipyard/src/main/scala/config/RocketConfigs.scala

**Type of change**: new feature 

Bump Gemmini for FP configs

---

generators/chipyard/src/main/scala/ConfigFragments.scala

API for setting Gemmini opcode changed a bit.

Bump gemmini for config changes

---

generators/firechip/src/main/scala/TargetConfigs.scala

Update some comments in TargetConfigs to reflect enhancements in UART div handling (courtesy of @aou). 

[FireChip] Update frequency selection related comments

---

generators/chipyard/src/main/scala/ConfigFragments.scala

Surprisingly there is no existing fragment to do this defined in rocketchip. Add our own here.

Add fragment to configure PMPs

---

generators/chipyard/src/main/scala/HarnessBinders.scala
generators/firechip/src/main/scala/BridgeBinders.scala

Add option to add async queues between chip-serialIO and harness serdes

---

docs/requirements.txt

Need this until the following is fixed: https://github.com/sphinx-doc/sphinx/issues/9063

Workaround docutils issue in doc generation

---

generators/firechip/src/main/scala/FireSim.scala

Supernode fails to elaborate using the new harness extensions to clock bridge instantiation.  I got a little carried away with stylistic changes (i can undo those), but this fixes that by permitting multiple requests to `requestClockRecordMap`. 

[firechip] Memoize Clock RecordMap creation to fix SuperNode

---

README.md

[skip ci] Update main README

---

.circleci/run-tests.sh

Bump FireMarshal to v1.12.0 (see firemarshal CHANGELOG for details)
Update the sha3 repo to get software changes used in the tutorial

Bump tutorial sw

---

scripts/build-toolchains.sh
scripts/init-submodules-no-riscv-tools-nolog.sh

Abe, wai. 
**Related issue**: #434  #435  #705  
**Type of change**: hipster bug fix 

Use a ZSH-compatible version of BASH_SOURCE[0]

---

.circleci/run-firesim-scala-tests.sh
generators/firechip/src/main/scala/FireSim.scala

Lots of new FireSim features have been added over the summer. This exposes them to CY dev.
I had to fix a few things in FireSim to make this work. 
See:
firesim/aws-fpga-firesim#45
firesim/firesim#827

Bump Firesim + Use ResetPulseBridge 

---

README.md
docs/index.rst

Forgot to update the NSF award in the documentation.

Ack. NSF award

---

README.md
docs/Prototyping/VCU118.rst
docs/index.rst

Sync `master` changes back with `dev`

Master -> Dev Sync

---

variables.mk

**Related issue**: #1052 
Backport of #1052

Force FIRRTL 1.4.1

---

common.mk
sims/vcs/Makefile
vcs.mk

**Related issue**: #1070 
**Impact**:  software change
- Add support for FSDB file format in VCS flow

Add support for FSDB

---

docs/VLSI/Advanced-Usage.rst
docs/VLSI/Basic-Flow.rst
docs/VLSI/Tutorial.rst
vlsi/example-asap7.yml
vlsi/example-tools.yml
vlsi/example-vlsi
vlsi/view_gds.py

Hammer now supports the (mostly) open-source r1p7 version of the ASAP7 PDK (ucb-bar/hammer#613). The tutorial and docs are updated to target this version bump.

ASAP7 r1p7

---

README.md

**Related issue**: Fixes #1099 
Fixed BOOM link in README since the HotChip website has changed.

Update BOOM reference in README

---

scripts/init-submodules-no-riscv-tools-nolog.sh

Fix prompt for validate check

---

CHANGELOG.md

Update changelog for 1.6.0 release.

Update changelog  for 1.6.0

---

.github/scripts/check-commit.sh
.readthedocs.yml
CONTRIBUTING.md
README.md

**Related PRs / Issues **:
**Impact**:
Small update to `main` branch to get CI to run. Also, update the `check-commit.sh` CI script to properly checkout all remote branches. Should fix the status badge.

Fix CI on `main`

---

CHANGELOG.md

**Related PRs / Issues **:
**Impact**:
See title.

Bump FireSim to 1.13.3 | Bump CL.md

---

README.md

This changes a single word in the README
**Impact**:

Fix Gemmini citation in README

---

.github/scripts/check-commit.sh
CHANGELOG.md

See firesim 1.13.4 changelog: https://github.com/firesim/firesim/blob/1.13.4/CHANGELOG.md
**Impact**:
I'm going to ship a new chipyard release based on current main after this goes in.

bump firesim for various fixes

---

project/plugins.sbt

This to support VSCode integration in FireSim and in Chipyard.
See: https://github.com/firesim/firesim/pull/1056 
**Impact**:

Add bloop back to sbt plugins.

---

scripts/repo-clean.sh

See title. This is a quick fix for now, all of these problems really need to be fixed in the appropriate submodules.

Script to get a clean git status after running standard initalization procedures

---

.github/workflows/chipyard-run-tests.yml

This will be reverted / debugged for the following release.
**Impact**:

Comment out firesim-run-test CI due to elfutils failure

---

CHANGELOG.md

Update CHANGELOG for 1.7.0

---

.github/scripts/check-commit.sh
.gitmodules

SiFive versions of repos will no longer be actively maintained so they've been transferred over to Chipsalliance. 
https://github.com/ucb-bar/chipyard/issues/1171
**Impact**:

Update SiFive submodules to CHIPS fork

---

scripts/build-toolchain-extra.sh

Follow up to #1224 
**Impact**:

Install espresso in build-toolchain-extra.sh

---

generators/chipyard/src/main/scala/config/RocketConfigs.scala

Fix comment bug introduced in #1224 
**Impact**:

[ci skip] Fix comment for FFTRocketGenerator

---

docs/VLSI/Sky130-Commercial-Tutorial.rst
docs/VLSI/Sky130-OpenROAD-Tutorial.rst

These were accidentally not included in the previous OpenROAD PR.

Sky130 Commercial/Openroad tutorial doc fixes

---

CHANGELOG.md

[ci skip] Update CHANGELOG.md for 1.8.0

---

CHANGELOG.md

[ci skip] Fix CHANGELOG.md for 1.8.0

---

docs/conf.py

Update the stable documentation to properly point to the most recent release. Other small fixes for if you are building the docs locally or on GH-A
Fixes #1240 
**Impact**:

Update stable docs

---

docs/Simulation/Software-RTL-Simulation.rst

Docs: Detail run-binary-debug option in Generating Waveforms documentation

---

docs/VLSI/ASAP7-Tutorial.rst
docs/VLSI/Sky130-Commercial-Tutorial.rst
vcs.mk
vlsi/Makefile

VPD is going away, we should default to generating FSDB.
If the user wants VPD, they set the `USE_VPD` flag. (`USE_FSDB` is ignored now, everything should default to `FSDB`).
**Impact**:

Default VCS simulators should generate FSDB

---

.readthedocs.yml

Missed pointing to conda lock file for RTD builds.
**Impact**:

Test conda lock for RTD

---

generators/tracegen/src/main/scala/Tile.scala

To fix the errors in https://github.com/chipsalliance/chisel3/pull/2751.
**Impact**:

fix: S-interpolator for assert, assume and printf

---

generators/chipyard/src/main/scala/config/BoomConfigs.scala
generators/chipyard/src/main/scala/config/HeteroConfigs.scala
generators/chipyard/src/main/scala/config/RocketConfigs.scala

With this change, configs should explicitly set the systembuswidth with a separate fragment. However, any systembuswidth can be set, without impacting functionality of boom/hwacha/gemmini.
**Impact**:

Decoupled sbus width from boom|hwacha|gemmini memory interface widths

---

scripts/build-setup.sh

Init FPGA submodules in build-setup.sh

---

.checkmake-config.ini
.pre-commit-config.yaml
common.mk

Add checkmake as pre-commit. 
**Impact**:

checkmake pre-commit hook

---

docs/Customization/Firrtl-Transforms.rst
docs/Simulation/Software-RTL-Simulation.rst

Sync docs with CIRCT changes

---

generators/chipyard/src/main/scala/SpikeTile.scala

Accidentally broke things when merging #1307 without rebasing first. This fixes that.
**Impact**:

Fix compile breaking due to merge conflict

---

conda-reqs/esp-tools.yaml
conda-reqs/riscv-tools.yaml
conda-requirements-riscv-tools.yaml

Use specific versions of riscv-tools/esp-tools

---

fpga/Makefile

#1354 had a temporary fix for #1355 by adding miscellaneous things to `SIM_FILE_REQS`.
This is a cleaner fix.
**Impact**:

fpga makefile clean fix

---

generators/chipyard/src/main/resources/csrc/cospike.cc

Writable bits in MISA is implementation-defined, so we can't follow spike here.
**Impact**:

Override spike's misa in cosim mode

---

build.sbt

See #1356. S/o @tymcauley for the fix
Fixes #1356
**Impact**:

Fix Chisel hierarchy API - Fixes #1356

---

generators/firechip/src/main/scala/BridgeBinders.scala
generators/firechip/src/main/scala/TargetConfigs.scala

See title. Need for local FPGA configuration/testing.
**Impact**:

Add a frag./config for MMIO only bridges

---

docs/Customization/Firrtl-Transforms.rst
docs/Tools/FIRRTL.rst

Update docs related to circt

---

.readthedocs.yml

Fixes #1401 (oops)
**Impact**:

Only HTML docs v2

---

scripts/build-setup.sh
scripts/init-submodules-no-riscv-tools-nolog.sh

See title. Done to avoid prompt getting lost in other output.
**Impact**:

Clear screen on prompt

---

tests/encoding.h
tests/hello.c
tests/mt-hello.c

Makes this more consistent with the other bare-metal tests that use encoding.h
**Impact**:

Use pk/encoding.h for hello/mt-hello

---

generators/chipyard/src/main/scala/Subsystem.scala

Fix no-uart configs

---

generators/chipyard/src/main/scala/System.scala

Fix support for no-bootROM systems

---

generators/firechip/src/main/scala/TargetConfigs.scala

Add 1GB / 4GB DRAM firechip configs for FireSim VCU118

---

sims/vcs/vcs.mk
sims/verilator/Makefile

Fix vcd/fst/fsdb waveform generation

---

.gitmodules
software/embench/build.sh

This builds bare-metal embench binaries
**Impact**:

Add embench build support

---

conda-reqs/chipyard.yaml
conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml
docs/Chipyard-Basics/Initial-Repo-Setup.rst

Copy of #1490 with small adjustments.
**Impact**:

Force conda-lock to v1

---

conda-reqs/chipyard.yaml
conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml
conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml

Downgrade cryptography | Pin linux sysroot

---

generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala

[ci skip] Fix broken docs link

---

.gitignore
generators/chipyard/src/main/scala/config/fragments/PeripheralFragments.scala

Sorry about this @T-K-233 , there's a very minor incompatibility issue in here with some existing configs. We'd normally just fix this the correct way, but there's an exceptional time constraint right now.
I'll open a PR re-adding this in a moment.
**Impact**:

Revert changes to peripheral fragments

---

CHANGELOG.md

[ci skip] Update changelog for 1.10.0

---

.mergify.yml

Bump mergify to check label

---

.github/workflows/chipyard-full-flow.yml

Weekly cron job to check that things like conda versions are fine.
**Impact**:

Add weekly CI cron job

---

docs/Customization/Custom-Chisel.rst

**Impact**:
The bit in the end with `lazy val chipyard` was out of date. (If you copied and pasted the line at the end of build.sbt, SBT would complain because `lazy val chipyard` is already defined somewhere in the middle of the file.) The new rewrite may be a bit more confusing, so if a maintainer feels like a rewording is necessary to make it more clear, that's ok :) 
Note: I don't have permissions to edit tags on a PR, so I am unable to add a `changelog:` label myself.

Updated part of "Integrating Custom Chisel Projects into the Generator Build System" docs which was out of date

---

.github/scripts/install-conda.sh
docs/Chipyard-Basics/Initial-Repo-Setup.rst

Bump Conda + Deprecate docker image docs

---

.github/scripts/check-commit.sh
README.md
docs/Chipyard-Basics/Initial-Repo-Setup.rst

bump firesim to main for 1.10.0 release

---

build.sbt

Currently Chipyard is including `barstools.iocell` as a separate project from the rest of barstools, and it does this by creating a new project rooted at `src` with its source directory rooted at `src/main/scala/barstools/iocell`. This causes problems for IDEs like IntelliJ which do not support having one source root from one project nested inside another source root from a different project.
By breaking out `barstools.iocell` into a separate project root, this should cause IDEs and similar tools to better understand the project structure, and makes it so that `iocell` is not in two projects at the same time.
This PR may still need to change more once we figure out how to integrate this project structure with barstools's CI / internal build.
barstools PR: …

barstools: move iocells to separate project root

---

generators/chipyard/src/main/resources/csrc/cospike.cc

Bump spike to latest

---

docs/Generators/SiFive-Generators.rst

Add documentation on sifive peripheral devices and example code of how to add them to the ChipConfig.
**Impact**:

Improve: SiFive peripheral device doumentation

---

generators/chipyard/src/main/resources/csrc/cospike.cc
generators/chipyard/src/main/resources/vsrc/cospike.v
generators/chipyard/src/main/scala/Cospike.scala
generators/chipyard/src/main/scala/harness/HarnessBinders.scala

Support variable VLEN cosim

---

generators/chipyard/src/main/scala/config/ChipConfigs.scala

Clarify fragments in ChipLikeRocketConfigs.scala

---

fpga/src/main/scala/vcu118/Configs.scala

Fix VCU118 freq adjustment configs

---

docs/Simulation/Software-RTL-Simulation.rst

Updated docs on waveform generation to match current workflow.

---

.github/scripts/check-commit.sh

These enforce we don't accidentally introduce dependencies on feature branches.
**Impact**:

[ci] Update check-commit with missing submodules

---

README.md

[ci skip] Fix funding ack

---

docs/Customization/Memory-Hierarchy.rst
generators/chipyard/src/main/scala/config/MemorySystemConfigs.scala
generators/chipyard/src/main/scala/config/PeripheralDeviceConfigs.scala
generators/chipyard/src/main/scala/config/RocketConfigs.scala

Move memory system configs to a separate configs file

---

generators/chipyard/src/main/scala/config/fragments/TileFragments.scala

Very useful for hierarchical PD flows
**Impact**:

Add RocketBoundaryBuffers fragment

---

variables.mk

Allow overriding generated-src dir name

---

scripts/build-setup.sh

This lets users skip CIRCT install if they need to manage their own custom CIRCT.
**Impact**:

Move CIRCT install to its own step in build-setup script

---

fpga/src/main/scala/arty/Configs.scala
fpga/src/main/scala/arty100t/Configs.scala
generators/chipyard/src/main/scala/config/AbstractConfig.scala
generators/chipyard/src/main/scala/config/NoCConfigs.scala
generators/chipyard/src/main/scala/config/NoCoreConfigs.scala
generators/chipyard/src/main/scala/config/RocketConfigs.scala
generators/chipyard/src/main/scala/config/SodorConfigs.scala

CHANGE: Set scratchpad as default config

---

.github/actions/create-conda-env/action.yml

Remove esp-conda-env from CI conda envs

---

common.mk

Fix check-submodule-status forcing rebuilds

---

fpga/src/main/scala/arty100t/Harness.scala

Fix missing childClock/childReset in Arty100THarness

---

docs/Chipyard-Basics/Chipyard-Components.rst

ADD: add information on Baremetal-IDE in docs

---

.github/scripts/check-commit.sh
.gitmodules
build.sbt
docs/Chipyard-Basics/Chipyard-Components.rst
docs/Customization/Custom-Chisel.rst
docs/Customization/Memory-Hierarchy.rst
docs/Generators/Rocket-Chip-Generators.rst
docs/Generators/Rocket-Chip.rst
docs/Generators/Rocket.rst
docs/Generators/index.rst
fpga/Makefile
scripts/tutorial-patches/build.sbt.patch

Rename blocks/cache submodules to match new chipsalliance ownership

---

common.mk

useful for debugging/checking value of a variable

Makefile: add print-FOO utility target that prints the value of a make variable

---

generators/chipyard/src/main/scala/config/MemorySystemConfigs.scala

For minimal-area experiments
**Impact**:

Add BroadcastCoherence rocket config

---

scripts/build-setup.sh

Fix typo in build-setup.sh

---

docs/Customization/Boot-Process.rst
docs/Generators/Hwacha.rst

Update dead doc links

---

generators/firechip/src/main/scala/TargetConfigs.scala

Add large boom cospike config

---

scripts/build-circt-from-source.sh

Fix build-circt-from-source

---

.gitmodules

REFACTOR: minor fix on code styling

---

generators/chipyard/src/main/scala/config/AbstractConfig.scala
generators/chipyard/src/main/scala/harness/HarnessBinders.scala

Add GPIOPunchthrough harnessbinder

---

docs/Chipyard-Basics/Initial-Repo-Setup.rst

Fix missing step in documentation.

---

fpga/src/main/scala/arty/Configs.scala
generators/chipyard/src/main/scala/config/fragments/ClockingFragments.scala
generators/chipyard/src/main/scala/config/fragments/SubsystemFragments.scala

Automatically set `DTSTimebase` to PBUS frequency

---

generators/chipyard/src/main/resources/csrc/spiketile.cc
generators/chipyard/src/main/scala/config/AccelConfigs.scala
generators/chipyard/src/main/scala/config/EE290RocketConfigs.scala
generators/chipyard/src/main/scala/config/RoCCAcceleratorConfigs.scala

You will need to pull a new version of Spike

Added in initial implementation of busy signal - I think it was working

---

.gitmodules
generators/chipyard/src/main/resources/csrc/spiketile.cc
generators/chipyard/src/main/scala/config/AccelConfigs.scala

Fix broken RoCC synchronization

Fix RoCC Synchronization

---

build.sbt

Detach build.sbt from firesim's build.sbt

---

generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala

Name all the generated ClockDomains

---

conda-reqs/chipyard-extended.yaml

add upper bound for python version to avoid incompatible packages

---

scripts/generate-ckpt.sh

Small QoL updates to checkpointing script.
**Impact**:

Update checkpointing script

---

generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala

Update ClockGroup aggregation error to be more descriptive

---

scripts/init-submodules-no-riscv-tools-nolog.sh

Non-recursive clone of compress-acc

---

scripts/build-circt-from-source.sh

Improve build-circt-from-source script for conda-less users

---

CHANGELOG.md

Release 1.12 changelog

---

.github/workflows/update-circt.yml

Shift CIRCT updates to weekly

---

generators/chipyard/src/main/scala/iobinders/IOBinders.scala

Support variable MMU capabilities in cosim

---

generators/chipyard/src/main/scala/config/NoCConfigs.scala

Bump constellation to fix support for AXI-converted TL

---

.github/scripts/check-commit.sh
.github/scripts/defaults.sh
.github/scripts/run-tests.sh
.github/workflows/chipyard-run-tests.yml
.gitmodules
build.sbt
common.mk
docs/Generators/Ara.rst
docs/Generators/Saturn.rst
docs/Generators/index.rst
generators/chipyard/src/main/scala/config/AraConfigs.scala
scripts/init-submodules-no-riscv-tools-nolog.sh
sims/verilator/Makefile

Integrate Ara vector unit

---

README.md

Mention vector units README

---

build.sbt

Update rerocc to support rerocc MMIO ctrl

---

docs/Generators/Saturn.rst

Vector bugfixes

---

.github/scripts/build-default-bitstreams.py
.github/scripts/ci_variables.py
.github/scripts/github_common.py
.github/workflows/firesim-cluster-tests.yml
common.mk
conda-reqs/chipyard-extended.yaml
conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64-lean.conda-lock.yml
conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml

WIP: More robust Github bitstream uploads

---

vlsi/example-designs/sky130-openroad-rockettile.yml
vlsi/example-designs/sky130-openroad.yml
vlsi/example-designs/sky130-rocket.yml
vlsi/example-sky130.yml

Update example floorplan used by Sky130 tutorials for changed SRAM instances.
**EDIT:** The YAML in example-designs also needs to be updated since it overrides `vlsi/example-sky130.yml` file when the `tutorial=` argument is passed to make. I've also found more issues with the layout stemming from margins not being aligned properly to the tracks, so I'll try to get all of these fixes rolled into this PR
**Impact**:
**CI Help**:
- …

Fix floorplan for example Sky130 VLSI flow

---

vlsi/example-sky130.yml

#2032 
**Impact**:
**CI Help**:

Fix accidentally included modifications to example yaml

---

generators/chipyard/src/main/scala/iobinders/IOBinders.scala

Bump testchipip with improve API for cosim with multiple RAMs

---

scripts/build-setup.sh

Avoid clean/delete of br-base
Build bare-base
https://github.com/firesim/firesim/pull/1835
**Impact**:
**CI Help**:

build-setup.sh precompile marshal sources

---

fpga/Makefile
fpga/src/main/scala/datastorm/Configs.scala
fpga/src/main/scala/datastorm/Harness.scala
fpga/src/main/scala/datastorm/HarnessBinders.scala

Add support for Intel/Altera FPGAs + Trenz Datastorm board

---

conda-reqs/chipyard-base.yaml
conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64-lean.conda-lock.yml
conda-reqs/conda-lock-reqs/conda-requirements-riscv-tools-linux-64.conda-lock.yml

VCS shared libraries require glibc 2.33 symbols, but when using VCS within a conda environment, the conda-provided GCC attempts to link against conda sysroot that was previously too old to provide those symbols. 
The error looked like this (reported by @schwarz-em):
VCS 2024.09 looks for as new as glibc 2.33, so it works with this bump to 2.34. Ubuntu 24.04 ships with 2.39.
We might need to bump this periodically in conjunction with OS/VCS updates if we were to keep using conda GCC for VCS.
**Impact**:
**CI Help**:
See `ci:*` for full …

Bump sysroot to fix VCS ABI incompatibility

---

generators/chipyard/src/main/scala/config/SaturnConfigs.scala

Bump rocket-chip

---

.gitmodules
scripts/init-vlsi.sh

`hammer-mentor-plugins` is a private (NDAed) repository and shouldn't be a prt of the default chipyard repo, since it will break scripts that fetch all submodules due to insufficient permissions.
**Impact**:
**CI Help**:

Remove hammer-mentor-plugins submodule from default chipyard

---

.github/CI_README.md

"gihub" link was broken
**Impact**:
**CI Help**:

Fix broken link/typo in CI_README.md

---

tests/.gitignore

Add .gitignore to tests for in-tree "cmake ." builds

---

docs/Advanced-Concepts/Top-Testharness.rst

Minor change based off a small issue that I definitely overthought, someone should check that my update is not lying though.
Explanation within: https://github.com/ucb-bar/chipyard/issues/1782
**Impact**:
**CI Help**:

Remove HasHierarchicalBusTopology mention in doc

---

generators/chipyard/src/main/scala/config/AbstractConfig.scala
generators/chipyard/src/main/scala/config/MMIOAcceleratorConfigs.scala
generators/chipyard/src/main/scala/example/GCD.scala
generators/chipyard/src/main/scala/iobinders/IOBinders.scala

Add option for externally clocked GCD peripheral example

---

scripts/utils.sh

Make scripts/init-submodules.sh mac friendly

---

common.mk
sims/vcs/Makefile
sims/verilator/Makefile
sims/xcelium/Makefile

Only check for RISCV if running a make target that references it

---

common.mk
variables.mk

Fix support for non-gnu SED

---

.gitmodules

fix: organize repos

---

README.md

Fix: reference link syntax
